import {
	convertToNextra4Config,
	// type ExistingNavMeta, // Commented out - only used by deprecated mergeNavMeta tests
	isApiPageEntry,
	isExternalLink,
	isNextra3xFile,
	isSeparator,
	isVirtualGroup,
	// type MenuNavMeta, // Commented out - only used by deprecated parseNavMeta tests
	// mergeNavMeta, // Deprecated - use MetaMerger.merge() instead
	NEXTRA_3X_FILES_TO_DELETE,
	// parseNavMeta, // Deprecated - use MetaMerger.validateSyntax() instead
	// parseNextra3NavMeta, // Deprecated - use MetaMerger instead
	parseNextra3ThemeConfig,
	type VirtualGroupMeta,
} from "./migration";
import { describe, expect, test } from "vitest";

describe("parseNextra3ThemeConfig", () => {
	test("extracts project link from theme config", () => {
		const content = `export default {
  project: {
    link: 'https://github.com/example/repo',
  },
}`;
		const { config, warnings } = parseNextra3ThemeConfig(content);
		expect(config.projectLink).toBe("https://github.com/example/repo");
		expect(warnings).toHaveLength(0);
	});

	test("extracts docsRepositoryBase from theme config", () => {
		const content = `export default {
  docsRepositoryBase: 'https://github.com/example/repo/tree/main/docs',
}`;
		const { config } = parseNextra3ThemeConfig(content);
		expect(config.docsRepositoryBase).toBe("https://github.com/example/repo/tree/main/docs");
	});

	test("extracts footer text and removes Jolli branding", () => {
		const content = `export default {
  footer: {
    text: 'My Site · Generated by Jolli',
  },
}`;
		const { config } = parseNextra3ThemeConfig(content);
		expect(config.footer).toBe("My Site");
	});

	test("extracts primary hue from CSS", () => {
		const content = `export default {
  head: (
    <>
      <style>{\`:root { --nextra-primary-hue: 180deg; }\`}</style>
    </>
  ),
}`;
		const { config } = parseNextra3ThemeConfig(content);
		expect(config.primaryHue).toBe(180);
	});

	test("extracts default theme", () => {
		const content = `export default {
  nextThemes: {
    defaultTheme: 'dark',
  },
}`;
		const { config } = parseNextra3ThemeConfig(content);
		expect(config.defaultTheme).toBe("dark");
	});

	test("extracts toc title", () => {
		const content = `export default {
  toc: {
    title: 'In This Article',
  },
}`;
		const { config } = parseNextra3ThemeConfig(content);
		expect(config.tocTitle).toBe("In This Article");
	});

	test("extracts sidebar collapse level", () => {
		const content = `export default {
  sidebar: {
    defaultMenuCollapseLevel: 3,
  },
}`;
		const { config } = parseNextra3ThemeConfig(content);
		expect(config.sidebarDefaultCollapseLevel).toBe(3);
	});

	test("warns about unsupported useNextSeoProps", () => {
		const content = `export default {
  useNextSeoProps() {
    return { titleTemplate: '%s – Site' }
  }
}`;
		const { warnings } = parseNextra3ThemeConfig(content);
		expect(warnings).toContain(
			"useNextSeoProps is not supported in Nextra 4.x - SEO is handled via metadata export",
		);
	});

	test("warns about custom navbar extraContent", () => {
		const content = `export default {
  navbar: {
    extraContent: <CustomButton />,
  },
}`;
		const { warnings } = parseNextra3ThemeConfig(content);
		expect(warnings).toContain(
			"navbar.extraContent is not directly supported - custom navbar components need manual migration",
		);
	});

	test("warns about JSX logo components", () => {
		const content = `export default {
  logo: <LogoLink />,
}`;
		const { warnings } = parseNextra3ThemeConfig(content);
		expect(warnings).toContain(
			"Custom logo components (JSX) cannot be automatically migrated - using text logo instead",
		);
	});

	test("handles complete real-world theme config", () => {
		const content = `import LogoLink from './components/LogoLink'
import NavbarApiButton from './components/NavbarApiButton'

export default {
  logo: <LogoLink />,
  project: {
    link: 'https://github.com/Jolli-sample-repos/test',
  },
  docsRepositoryBase: 'https://github.com/Jolli-sample-repos/test',
  editLink: {
    component: null,
  },
  feedback: {
    content: null,
  },
  sidebar: {
    defaultMenuCollapseLevel: 2,
  },
  toc: {
    title: 'On This Page',
  },
  head: (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <style>{\`:root { --nextra-primary-hue: 212deg; }\`}</style>
    </>
  ),
  darkMode: true,
  nextThemes: {
    defaultTheme: 'system',
  },
  navbar: {
    extraContent: <NavbarApiButton />,
  },
  footer: {
    text: 'test · Generated by Jolli',
  },
  useNextSeoProps() {
    return {
      titleTemplate: '%s – test'
    }
  }
}`;
		const { config, warnings } = parseNextra3ThemeConfig(content);

		expect(config.projectLink).toBe("https://github.com/Jolli-sample-repos/test");
		expect(config.docsRepositoryBase).toBe("https://github.com/Jolli-sample-repos/test");
		expect(config.footer).toBe("test");
		expect(config.primaryHue).toBe(212);
		expect(config.defaultTheme).toBe("system");
		expect(config.tocTitle).toBe("On This Page");
		expect(config.sidebarDefaultCollapseLevel).toBe(2);

		// Should have warnings for unsupported features
		expect(warnings.length).toBeGreaterThan(0);
	});
});

// ===== DEPRECATED: Tests for parseNextra3NavMeta - see MetaMerger.test.ts =====
// describe("parseNextra3NavMeta", () => {
// 	test("parses simple _meta.js content", () => {
// 		const content = `export default {
//   "index": "Home",
//   "getting-started": "Getting Started",
//   "api-reference": "API Reference"
// }`;
// 		const meta = parseNextra3NavMeta(content);
//
// 		expect(meta).toEqual({
// 			index: "Home",
// 			"getting-started": "Getting Started",
// 			"api-reference": "API Reference",
// 		});
// 	});
//
// 	test("parses _meta.js with single quotes", () => {
// 		const content = `export default {
//   'index': 'Home',
//   'about': 'About Us'
// }`;
// 		const meta = parseNextra3NavMeta(content);
//
// 		expect(meta).toEqual({
// 			index: "Home",
// 			about: "About Us",
// 		});
// 	});
//
// 	test("handles empty _meta.js", () => {
// 		const content = "export default {}";
// 		const meta = parseNextra3NavMeta(content);
// 		expect(meta).toEqual({});
// 	});
// });

// ===== DEPRECATED: Tests for parseNavMeta - see MetaMerger.test.ts =====
// describe("parseNavMeta", () => {
// 	test("parses flat _meta.ts content", () => {
// 		const content = `export default {
//   'index': 'Home',
//   'getting-started': 'Getting Started',
//   'api-reference': 'API Reference'
// }`;
// 		const meta = parseNavMeta(content);
//
// 		expect(meta).toEqual({
// 			index: "Home",
// 			"getting-started": "Getting Started",
// 			"api-reference": "API Reference",
// 		});
// 	});
//
// 	test("parses _meta.ts with virtual groups", () => {
// 		const content = `export default {
//   index: 'Home',
//   docs: {
//     title: 'Docs',
//     type: 'page',
//     items: {
//       introduction: 'Introduction',
//       'getting-started': 'Getting Started',
//     },
//   },
//   'change-log': 'Change Log',
// }`;
// 		const meta = parseNavMeta(content);
//
// 		expect(meta.index).toBe("Home");
// 		expect(meta["change-log"]).toBe("Change Log");
//
// 		const docsEntry = meta.docs as VirtualGroupMeta;
// 		expect(docsEntry.title).toBe("Docs");
// 		expect(docsEntry.type).toBe("page");
// 		expect(docsEntry.items).toEqual({
// 			introduction: "Introduction",
// 			"getting-started": "Getting Started",
// 		});
// 	});
//
// 	test("parses _meta.ts with API page entries", () => {
// 		const content = `export default {
//   index: 'Home',
//   'api-jolli': {
//     title: 'Jolli API',
//     type: 'page',
//     href: '/api-docs-jolli.html',
//   },
// }`;
// 		const meta = parseNavMeta(content);
//
// 		expect(meta.index).toBe("Home");
// 		expect(meta["api-jolli"]).toEqual({
// 			title: "Jolli API",
// 			type: "page",
// 			href: "/api-docs-jolli.html",
// 		});
// 	});
//
// 	test("parses _meta.ts with separators", () => {
// 		const content = `export default {
//   index: 'Home',
//   '---': { type: 'separator' },
//   about: 'About',
// }`;
// 		const meta = parseNavMeta(content);
//
// 		expect(meta.index).toBe("Home");
// 		expect(meta["---"]).toEqual({ type: "separator" });
// 		expect(meta.about).toBe("About");
// 	});
//
// 	test("parses _meta.ts with titled separators", () => {
// 		const content = `export default {
//   index: 'Home',
//   '-- docs': {
//     type: 'separator',
//     title: 'Docs'
//   },
//   introduction: 'Introduction',
// }`;
// 		const meta = parseNavMeta(content);
//
// 		expect(meta.index).toBe("Home");
// 		expect(meta["-- docs"]).toEqual({ type: "separator", title: "Docs" });
// 		expect(meta.introduction).toBe("Introduction");
// 	});
//
// 	test("parses complex _meta.ts with all entry types", () => {
// 		const content = `export default {
//   index: 'Home',
//
//   docs: {
//     title: 'Docs',
//     type: 'page',
//     items: {
//       introduction: 'Introduction',
//       'get-start-document': 'Get start document',
//     },
//   },
//
//   articles: {
//     title: 'Articles',
//     type: 'page',
//     items: {
//       'test-added-article': 'Test added article',
//     },
//   },
//
//   experiments: {
//     title: 'Experiments',
//     type: 'page',
//     items: {
//       testtest: 'testtest',
//       test: 'test',
//     },
//   },
//
//   'change-log': 'Change Log',
//
//   'api-jolli': {
//     title: 'Jolli',
//     type: 'page',
//     href: '/api-docs-jolli.html',
//   },
// }`;
// 		const meta = parseNavMeta(content);
//
// 		// Check flat entries
// 		expect(meta.index).toBe("Home");
// 		expect(meta["change-log"]).toBe("Change Log");
//
// 		// Check virtual groups
// 		const docsEntry = meta.docs as VirtualGroupMeta;
// 		expect(docsEntry.title).toBe("Docs");
// 		expect(docsEntry.items.introduction).toBe("Introduction");
// 		expect(docsEntry.items["get-start-document"]).toBe("Get start document");
//
// 		const articlesEntry = meta.articles as VirtualGroupMeta;
// 		expect(articlesEntry.title).toBe("Articles");
// 		expect(articlesEntry.items["test-added-article"]).toBe("Test added article");
//
// 		const experimentsEntry = meta.experiments as VirtualGroupMeta;
// 		expect(experimentsEntry.title).toBe("Experiments");
// 		expect(experimentsEntry.items.testtest).toBe("testtest");
// 		expect(experimentsEntry.items.test).toBe("test");
//
// 		// Check API page entry
// 		expect(meta["api-jolli"]).toEqual({
// 			title: "Jolli",
// 			type: "page",
// 			href: "/api-docs-jolli.html",
// 		});
// 	});
//
// 	test("parses menu type virtual groups", () => {
// 		const content = `export default {
//   menu: {
//     title: 'Menu',
//     type: 'menu',
//     items: {
//       item1: 'Item 1',
//       item2: 'Item 2',
//     },
//   },
// }`;
// 		const meta = parseNavMeta(content);
//
// 		const menuEntry = meta.menu as VirtualGroupMeta;
// 		expect(menuEntry.title).toBe("Menu");
// 		expect(menuEntry.type).toBe("menu");
// 		expect(menuEntry.items).toEqual({
// 			item1: "Item 1",
// 			item2: "Item 2",
// 		});
// 	});
//
// 	test("parses MenuNavMeta for API Reference dropdown with multiple specs", () => {
// 		const content = `export default {
//   'index': { display: 'hidden' },
//   'getting-started': 'Getting Started',
//   'api-reference': {
//     title: 'My Custom API Title',
//     type: 'menu',
//     items: {
//       'petstore': { title: 'Pet Store API', href: '/api-docs/petstore' },
//       'users-api': { title: 'Custom Users Title', href: '/api-docs/users-api' }
//     }
//   }
// }`;
// 		const meta = parseNavMeta(content);
//
// 		// Should parse as MenuNavMeta, not VirtualGroupMeta
// 		const apiRef = meta["api-reference"] as MenuNavMeta;
// 		expect(apiRef.title).toBe("My Custom API Title");
// 		expect(apiRef.type).toBe("menu");
// 		expect(apiRef.items).toEqual({
// 			petstore: { title: "Pet Store API", href: "/api-docs/petstore" },
// 			"users-api": { title: "Custom Users Title", href: "/api-docs/users-api" },
// 		});
// 	});
//
// 	test("falls back to legacy parser for non-export-default content", () => {
// 		const content = `{
//   "index": "Home",
//   "about": "About"
// }`;
// 		const meta = parseNavMeta(content);
//
// 		// Legacy parser extracts string pairs
// 		expect(meta.index).toBe("Home");
// 		expect(meta.about).toBe("About");
// 	});
//
// 	test("handles empty _meta.ts", () => {
// 		const content = "export default {}";
// 		const meta = parseNavMeta(content);
// 		expect(meta).toEqual({});
// 	});
//
// 	test("handles _meta.ts with trailing semicolon", () => {
// 		const content = `export default {
//   index: 'Home',
//   about: 'About',
// };`;
// 		const meta = parseNavMeta(content);
//
// 		expect(meta.index).toBe("Home");
// 		expect(meta.about).toBe("About");
// 	});
// });

describe("convertToNextra4Config", () => {
	test("converts basic config", () => {
		const nextra3Config = {
			projectLink: "https://github.com/example/repo",
			primaryHue: 180,
			defaultTheme: "dark" as const,
			tocTitle: "Contents",
		};

		const config = convertToNextra4Config(nextra3Config, "my-site", "My Site");

		expect(config.logo).toBe("My Site");
		expect(config.projectLink).toBe("https://github.com/example/repo");
		expect(config.primaryHue).toBe(180);
		expect(config.defaultTheme).toBe("dark");
		expect(config.tocTitle).toBe("Contents");
	});

	test("uses default docsRepositoryBase if not provided", () => {
		const config = convertToNextra4Config({}, "my-site", "My Site");
		expect(config.docsRepositoryBase).toBe("https://github.com/Jolli-sample-repos/my-site");
	});

	test("preserves custom docsRepositoryBase", () => {
		const config = convertToNextra4Config(
			{ docsRepositoryBase: "https://github.com/custom/repo" },
			"my-site",
			"My Site",
		);
		expect(config.docsRepositoryBase).toBe("https://github.com/custom/repo");
	});

	test("preserves footer text", () => {
		const config = convertToNextra4Config({ footer: "My Footer" }, "my-site", "My Site");
		expect(config.footer).toBe("My Footer");
	});

	test("preserves sidebarDefaultCollapseLevel", () => {
		const config = convertToNextra4Config({ sidebarDefaultCollapseLevel: 3 }, "my-site", "My Site");
		expect(config.sidebarDefaultCollapseLevel).toBe(3);
	});
});

// ===== DEPRECATED: Tests for mergeNavMeta - see MetaMerger.test.ts =====
// describe("mergeNavMeta", () => {
// 	test("preserves existing entries in order", () => {
// 		const existing = {
// 			index: "Home",
// 			introduction: "🚀 Getting Started",
// 			"api-guide": "API Guide",
// 		};
// 		const newSlugs = ["index", "introduction", "api-guide"];
// 		const titles = new Map([
// 			["index", "Home"],
// 			["introduction", "Introduction"],
// 			["api-guide", "API Guide"],
// 		]);
//
// 		const result = mergeNavMeta(existing, newSlugs, titles);
//
// 		// Should preserve custom title "🚀 Getting Started"
// 		expect(result.meta.introduction).toBe("🚀 Getting Started");
// 		// Order should be preserved
// 		const keys = Object.keys(result.meta);
// 		expect(keys).toEqual(["index", "introduction", "api-guide"]);
// 		// No entries should be removed
// 		expect(result.removedEntries).toEqual([]);
// 	});
//
// 	test("adds new articles at the end", () => {
// 		const existing = {
// 			index: "Home",
// 			introduction: "Introduction",
// 		};
// 		const newSlugs = ["index", "introduction", "new-article"];
// 		const titles = new Map([
// 			["index", "Home"],
// 			["introduction", "Introduction"],
// 			["new-article", "New Article"],
// 		]);
//
// 		const result = mergeNavMeta(existing, newSlugs, titles);
//
// 		const keys = Object.keys(result.meta);
// 		expect(keys).toEqual(["index", "introduction", "new-article"]);
// 		expect(result.meta["new-article"]).toBe("New Article");
// 		expect(result.removedEntries).toEqual([]);
// 	});
//
// 	test("removes deleted articles", () => {
// 		const existing = {
// 			index: "Home",
// 			introduction: "Introduction",
// 			"old-article": "Old Article",
// 		};
// 		const newSlugs = ["index", "introduction"];
// 		const titles = new Map([
// 			["index", "Home"],
// 			["introduction", "Introduction"],
// 		]);
// 		const deletedSlugs = ["old-article"];
//
// 		const result = mergeNavMeta(existing, newSlugs, titles, deletedSlugs);
//
// 		expect(result.meta["old-article"]).toBeUndefined();
// 		const keys = Object.keys(result.meta);
// 		expect(keys).toEqual(["index", "introduction"]);
// 		// "old-article" should be in removedEntries
// 		expect(result.removedEntries).toContain("old-article");
// 	});
//
// 	test("removes entries not in newArticleSlugs (deselection without explicit deletion)", () => {
// 		const existing = {
// 			index: "Home",
// 			introduction: "Introduction",
// 			"deselected-article": "Deselected Article",
// 			"another-orphan": "Another Orphan",
// 		};
// 		// These are the only articles being generated now
// 		const newSlugs = ["index", "introduction"];
// 		const titles = new Map([
// 			["index", "Home"],
// 			["introduction", "Introduction"],
// 		]);
// 		// No explicit deletedSlugs - the entries are just not in newSlugs anymore
//
// 		const result = mergeNavMeta(existing, newSlugs, titles);
//
// 		// Deselected articles should be removed
// 		expect(result.meta["deselected-article"]).toBeUndefined();
// 		expect(result.meta["another-orphan"]).toBeUndefined();
// 		// Only kept articles should remain
// 		const keys = Object.keys(result.meta);
// 		expect(keys).toEqual(["index", "introduction"]);
// 		// Removed entries should be tracked for logging
// 		expect(result.removedEntries).toContain("deselected-article");
// 		expect(result.removedEntries).toContain("another-orphan");
// 		expect(result.removedEntries).toHaveLength(2);
// 	});
//
// 	test("returns removed entries in result for logging", () => {
// 		const existing = {
// 			index: "Home",
// 			"article-a": "Article A",
// 			"article-b": "Article B",
// 			"orphan-1": "Orphan 1",
// 			"orphan-2": "Orphan 2",
// 		};
// 		const newSlugs = ["index", "article-a", "article-b"];
// 		const titles = new Map([
// 			["index", "Home"],
// 			["article-a", "Article A"],
// 			["article-b", "Article B"],
// 		]);
//
// 		const result = mergeNavMeta(existing, newSlugs, titles);
//
// 		// Check the meta has only the expected entries
// 		expect(Object.keys(result.meta)).toEqual(["index", "article-a", "article-b"]);
// 		// Check removed entries are tracked
// 		expect(result.removedEntries).toContain("orphan-1");
// 		expect(result.removedEntries).toContain("orphan-2");
// 		expect(result.removedEntries).toHaveLength(2);
// 	});
//
// 	test("ensures index is always first", () => {
// 		const existing = {
// 			about: "About",
// 			index: "Home",
// 		};
// 		const newSlugs = ["about", "index"];
// 		const titles = new Map([
// 			["about", "About"],
// 			["index", "Home"],
// 		]);
//
// 		const result = mergeNavMeta(existing, newSlugs, titles);
//
// 		const keys = Object.keys(result.meta);
// 		expect(keys[0]).toBe("index");
// 	});
//
// 	test("handles empty existing meta", () => {
// 		const newSlugs = ["index", "introduction"];
// 		const titles = new Map([
// 			["index", "Home"],
// 			["introduction", "Introduction"],
// 		]);
//
// 		const result = mergeNavMeta({}, newSlugs, titles);
//
// 		expect(result.meta).toEqual({
// 			index: "Home",
// 			introduction: "Introduction",
// 		});
// 		expect(result.removedEntries).toEqual([]);
// 	});
//
// 	test("does not include index in removedEntries", () => {
// 		// Edge case: if existing has index but newSlugs doesn't, index shouldn't be in removedEntries
// 		// because index is regenerated anyway
// 		const existing = {
// 			index: "Old Home",
// 			"only-article": "Only Article",
// 		};
// 		// New slugs don't include index (edge case) - but index is always added back
// 		const newSlugs = ["only-article"];
// 		const titles = new Map([["only-article", "Only Article"]]);
//
// 		const result = mergeNavMeta(existing, newSlugs, titles);
//
// 		// Index should not be tracked as removed even though it's filtered out
// 		// (because index is special and always regenerated)
// 		expect(result.removedEntries).not.toContain("index");
// 	});
// });

describe("NEXTRA_3X_FILES_TO_DELETE", () => {
	test("includes Pages Router files with all extensions", () => {
		// .js extension
		expect(NEXTRA_3X_FILES_TO_DELETE).toContain("pages/_app.js");
		expect(NEXTRA_3X_FILES_TO_DELETE).toContain("pages/_document.js");
		expect(NEXTRA_3X_FILES_TO_DELETE).toContain("pages/_error.js");
		expect(NEXTRA_3X_FILES_TO_DELETE).toContain("pages/404.js");
		// .jsx extension
		expect(NEXTRA_3X_FILES_TO_DELETE).toContain("pages/_app.jsx");
		expect(NEXTRA_3X_FILES_TO_DELETE).toContain("pages/_document.jsx");
		expect(NEXTRA_3X_FILES_TO_DELETE).toContain("pages/_error.jsx");
		expect(NEXTRA_3X_FILES_TO_DELETE).toContain("pages/404.jsx");
		// .ts extension
		expect(NEXTRA_3X_FILES_TO_DELETE).toContain("pages/_app.ts");
		expect(NEXTRA_3X_FILES_TO_DELETE).toContain("pages/_document.ts");
		expect(NEXTRA_3X_FILES_TO_DELETE).toContain("pages/_error.ts");
		expect(NEXTRA_3X_FILES_TO_DELETE).toContain("pages/404.ts");
		// .tsx extension
		expect(NEXTRA_3X_FILES_TO_DELETE).toContain("pages/_app.tsx");
		expect(NEXTRA_3X_FILES_TO_DELETE).toContain("pages/_document.tsx");
		expect(NEXTRA_3X_FILES_TO_DELETE).toContain("pages/_error.tsx");
		expect(NEXTRA_3X_FILES_TO_DELETE).toContain("pages/404.tsx");
		// Other Pages Router files
		expect(NEXTRA_3X_FILES_TO_DELETE).toContain("pages/_meta.js");
		expect(NEXTRA_3X_FILES_TO_DELETE).toContain("pages/index.mdx");
	});

	test("includes theme config files with all extensions", () => {
		expect(NEXTRA_3X_FILES_TO_DELETE).toContain("theme.config.js");
		expect(NEXTRA_3X_FILES_TO_DELETE).toContain("theme.config.jsx");
		expect(NEXTRA_3X_FILES_TO_DELETE).toContain("theme.config.ts");
		expect(NEXTRA_3X_FILES_TO_DELETE).toContain("theme.config.tsx");
	});

	test("includes old component files", () => {
		expect(NEXTRA_3X_FILES_TO_DELETE).toContain("components/LogoLink.tsx");
		expect(NEXTRA_3X_FILES_TO_DELETE).toContain("components/NavbarApiButton.tsx");
	});
});

describe("isNextra3xFile", () => {
	test("returns true for Nextra 3.x files with various extensions", () => {
		// .jsx
		expect(isNextra3xFile("theme.config.jsx")).toBe(true);
		expect(isNextra3xFile("pages/_app.jsx")).toBe(true);
		// .js
		expect(isNextra3xFile("theme.config.js")).toBe(true);
		expect(isNextra3xFile("pages/_app.js")).toBe(true);
		expect(isNextra3xFile("pages/_meta.js")).toBe(true);
		// .tsx
		expect(isNextra3xFile("pages/_document.tsx")).toBe(true);
		// .ts
		expect(isNextra3xFile("pages/_document.ts")).toBe(true);
	});

	test("returns false for Nextra 4.x files", () => {
		expect(isNextra3xFile("app/layout.tsx")).toBe(false);
		expect(isNextra3xFile("content/_meta.ts")).toBe(false);
		expect(isNextra3xFile("mdx-components.tsx")).toBe(false);
	});
});

describe("type guards", () => {
	describe("isVirtualGroup", () => {
		test("returns true for virtual group entries", () => {
			const entry: VirtualGroupMeta = {
				title: "Docs",
				type: "page",
				items: { introduction: "Introduction" },
			};
			expect(isVirtualGroup(entry)).toBe(true);
		});

		test("returns true for menu type virtual groups", () => {
			const entry: VirtualGroupMeta = {
				title: "Menu",
				type: "menu",
				items: { item1: "Item 1" },
			};
			expect(isVirtualGroup(entry)).toBe(true);
		});

		test("returns false for string entries", () => {
			expect(isVirtualGroup("Title" as unknown as VirtualGroupMeta)).toBe(false);
		});

		test("returns false for API page entries", () => {
			const entry = { title: "API", type: "page" as const, href: "/api.html" };
			expect(isVirtualGroup(entry)).toBe(false);
		});

		test("returns false for separator entries", () => {
			const entry = { type: "separator" as const };
			expect(isVirtualGroup(entry)).toBe(false);
		});
	});

	describe("isApiPageEntry", () => {
		test("returns true for API page entries with href", () => {
			const entry = { title: "API", type: "page" as const, href: "/api.html" };
			expect(isApiPageEntry(entry)).toBe(true);
		});

		test("returns false for virtual groups", () => {
			const entry: VirtualGroupMeta = {
				title: "Docs",
				type: "page",
				items: { intro: "Intro" },
			};
			expect(isApiPageEntry(entry)).toBe(false);
		});

		test("returns false for string entries", () => {
			expect(isApiPageEntry("Title" as unknown as VirtualGroupMeta)).toBe(false);
		});

		test("returns false for external link entries (no type field)", () => {
			const entry = { title: "Contact", href: "mailto:hi@example.com" };
			expect(isApiPageEntry(entry)).toBe(false);
		});
	});

	describe("isExternalLink", () => {
		test("returns true for external link with title and href", () => {
			const entry = { title: "Contact Us", href: "mailto:hi@example.com" };
			expect(isExternalLink(entry)).toBe(true);
		});

		test("returns true for external link with just href", () => {
			const entry = { href: "https://github.com/example" };
			expect(isExternalLink(entry)).toBe(true);
		});

		test("returns false for API page entries (has type: page)", () => {
			const entry = { title: "API", type: "page" as const, href: "/api.html" };
			expect(isExternalLink(entry)).toBe(false);
		});

		test("returns false for virtual groups", () => {
			const entry: VirtualGroupMeta = {
				title: "Docs",
				type: "page",
				items: { intro: "Intro" },
			};
			expect(isExternalLink(entry)).toBe(false);
		});

		test("returns false for string entries", () => {
			expect(isExternalLink("Title")).toBe(false);
		});

		test("returns false for separator entries", () => {
			const entry = { type: "separator" as const };
			expect(isExternalLink(entry)).toBe(false);
		});
	});

	describe("isSeparator", () => {
		test("returns true for separator entries", () => {
			const entry = { type: "separator" as const };
			expect(isSeparator(entry)).toBe(true);
		});

		test("returns false for virtual groups", () => {
			const entry: VirtualGroupMeta = {
				title: "Docs",
				type: "page",
				items: { intro: "Intro" },
			};
			expect(isSeparator(entry)).toBe(false);
		});

		test("returns false for API page entries", () => {
			const entry = { title: "API", type: "page" as const, href: "/api.html" };
			expect(isSeparator(entry)).toBe(false);
		});
	});
});

// ===== DEPRECATED: Tests for mergeNavMeta with nested virtual groups - see MetaMerger.test.ts =====
// describe("mergeNavMeta with nested virtual groups", () => {
// 	test("preserves virtual groups with valid items", () => {
// 		const existing: ExistingNavMeta = {
// 			index: "Home",
// 			docs: {
// 				title: "Docs",
// 				type: "page",
// 				items: {
// 					introduction: "Introduction",
// 					"getting-started": "Getting Started",
// 				},
// 			},
// 		};
// 		const newSlugs = ["index", "introduction", "getting-started"];
// 		const titles = new Map([
// 			["index", "Home"],
// 			["introduction", "Introduction"],
// 			["getting-started", "Getting Started"],
// 		]);
//
// 		const result = mergeNavMeta(existing, newSlugs, titles);
//
// 		expect(result.meta.index).toBe("Home");
// 		const docsEntry = result.meta.docs as VirtualGroupMeta;
// 		expect(docsEntry.items).toEqual({
// 			introduction: "Introduction",
// 			"getting-started": "Getting Started",
// 		});
// 		expect(result.removedEntries).toEqual([]);
// 	});
//
// 	test("removes orphaned items from virtual groups", () => {
// 		const existing: ExistingNavMeta = {
// 			docs: {
// 				title: "Docs",
// 				type: "page",
// 				items: {
// 					introduction: "Introduction",
// 					"deleted-article": "Deleted Article",
// 				},
// 			},
// 		};
// 		const newSlugs = ["introduction"]; // deleted-article removed
// 		const titles = new Map([["introduction", "Introduction"]]);
//
// 		const result = mergeNavMeta(existing, newSlugs, titles);
//
// 		const docsEntry = result.meta.docs as VirtualGroupMeta;
// 		expect(docsEntry.items).toEqual({
// 			introduction: "Introduction",
// 		});
// 		expect(result.removedEntries).toContain("docs/deleted-article");
// 	});
//
// 	test("removes empty virtual groups", () => {
// 		const existing: ExistingNavMeta = {
// 			index: "Home",
// 			docs: {
// 				title: "Docs",
// 				type: "page",
// 				items: {
// 					"deleted-article": "Deleted Article",
// 				},
// 			},
// 		};
// 		const newSlugs = ["index"]; // No articles match the group's items
// 		const titles = new Map([["index", "Home"]]);
//
// 		const result = mergeNavMeta(existing, newSlugs, titles);
//
// 		expect(result.meta.docs).toBeUndefined();
// 		expect(result.removedEntries).toContain("docs/deleted-article");
// 		expect(result.removedEntries).toContain("docs (empty group)");
// 	});
//
// 	test("preserves API page entries (not article-based)", () => {
// 		const existing: ExistingNavMeta = {
// 			"api-jolli": {
// 				title: "Jolli API",
// 				type: "page",
// 				href: "/api-docs-jolli.html",
// 			},
// 		};
// 		const newSlugs: Array<string> = [];
// 		const titles = new Map<string, string>();
//
// 		const result = mergeNavMeta(existing, newSlugs, titles);
//
// 		expect(result.meta["api-jolli"]).toEqual({
// 			title: "Jolli API",
// 			type: "page",
// 			href: "/api-docs-jolli.html",
// 		});
// 		expect(result.removedEntries).toEqual([]);
// 	});
//
// 	test("preserves separators", () => {
// 		const existing: ExistingNavMeta = {
// 			index: "Home",
// 			"---": { type: "separator" },
// 			about: "About",
// 		};
// 		const newSlugs = ["index", "about"];
// 		const titles = new Map([
// 			["index", "Home"],
// 			["about", "About"],
// 		]);
//
// 		const result = mergeNavMeta(existing, newSlugs, titles);
//
// 		expect(result.meta["---"]).toEqual({ type: "separator" });
// 	});
//
// 	test("adds new articles at top level, not inside groups", () => {
// 		const existing: ExistingNavMeta = {
// 			docs: {
// 				title: "Docs",
// 				type: "page",
// 				items: { "old-article": "Old Article" },
// 			},
// 		};
// 		const newSlugs = ["old-article", "new-article"];
// 		const titles = new Map([
// 			["old-article", "Old Article"],
// 			["new-article", "New Article"],
// 		]);
//
// 		const result = mergeNavMeta(existing, newSlugs, titles);
//
// 		// New article added at top level, not inside group
// 		expect(result.meta["new-article"]).toBe("New Article");
// 		// Old article preserved in group
// 		const docsEntry = result.meta.docs as VirtualGroupMeta;
// 		expect(docsEntry.items["old-article"]).toBe("Old Article");
// 	});
//
// 	test("handles complex structure with multiple groups", () => {
// 		const existing: ExistingNavMeta = {
// 			index: "Home",
// 			docs: {
// 				title: "Docs",
// 				type: "page",
// 				items: {
// 					introduction: "Introduction",
// 					"get-started-document": "Get start document",
// 				},
// 			},
// 			articles: {
// 				title: "Articles",
// 				type: "page",
// 				items: {
// 					"test-added-article": "Test added article",
// 				},
// 			},
// 			"change-log": "Change Log",
// 			"api-jolli": {
// 				title: "Jolli",
// 				type: "page",
// 				href: "/api-docs-jolli.html",
// 			},
// 		};
// 		const newSlugs = ["index", "introduction", "change-log"];
// 		const titles = new Map([
// 			["index", "Home"],
// 			["introduction", "Introduction"],
// 			["change-log", "Change Log"],
// 		]);
//
// 		const result = mergeNavMeta(existing, newSlugs, titles);
//
// 		// Index should be first
// 		expect(Object.keys(result.meta)[0]).toBe("index");
// 		// Docs group should remain with filtered items
// 		const docsEntry = result.meta.docs as VirtualGroupMeta;
// 		expect(docsEntry.items.introduction).toBe("Introduction");
// 		expect(docsEntry.items["get-started-document"]).toBeUndefined();
// 		// Articles group should be removed (empty after filtering)
// 		expect(result.meta.articles).toBeUndefined();
// 		// change-log should remain
// 		expect(result.meta["change-log"]).toBe("Change Log");
// 		// API page should remain
// 		expect(result.meta["api-jolli"]).toEqual({
// 			title: "Jolli",
// 			type: "page",
// 			href: "/api-docs-jolli.html",
// 		});
// 		// Check removed entries
// 		expect(result.removedEntries).toContain("docs/get-started-document");
// 		expect(result.removedEntries).toContain("articles/test-added-article");
// 		expect(result.removedEntries).toContain("articles (empty group)");
// 	});
//
// 	test("preserves user customizations inside virtual groups", () => {
// 		const existing: ExistingNavMeta = {
// 			docs: {
// 				title: "Documentation",
// 				type: "page",
// 				items: {
// 					introduction: "🚀 Getting Started", // User customized title with emoji
// 					guide: "Developer Guide",
// 				},
// 			},
// 		};
// 		const newSlugs = ["introduction", "guide"];
// 		const titles = new Map([
// 			["introduction", "Introduction"], // Generator title (different)
// 			["guide", "Guide"], // Generator title (different)
// 		]);
//
// 		const result = mergeNavMeta(existing, newSlugs, titles);
//
// 		const docsEntry = result.meta.docs as VirtualGroupMeta;
// 		// Should preserve user's custom titles
// 		expect(docsEntry.items.introduction).toBe("🚀 Getting Started");
// 		expect(docsEntry.items.guide).toBe("Developer Guide");
// 	});
//
// 	test("handles menu type virtual groups", () => {
// 		const existing: ExistingNavMeta = {
// 			menu: {
// 				title: "Menu",
// 				type: "menu",
// 				items: {
// 					item1: "Item 1",
// 					item2: "Item 2",
// 				},
// 			},
// 		};
// 		const newSlugs = ["item1"];
// 		const titles = new Map([["item1", "Item 1"]]);
//
// 		const result = mergeNavMeta(existing, newSlugs, titles);
//
// 		const menuEntry = result.meta.menu as VirtualGroupMeta;
// 		expect(menuEntry.type).toBe("menu");
// 		expect(menuEntry.items).toEqual({ item1: "Item 1" });
// 		expect(result.removedEntries).toContain("menu/item2");
// 	});
//
// 	test("maintains backward compatibility with flat meta structures", () => {
// 		// Test that the function still works with simple flat structures
// 		const existing: ExistingNavMeta = {
// 			index: "Home",
// 			introduction: "🚀 Getting Started",
// 			"api-guide": "API Guide",
// 		};
// 		const newSlugs = ["index", "introduction", "api-guide"];
// 		const titles = new Map([
// 			["index", "Home"],
// 			["introduction", "Introduction"],
// 			["api-guide", "API Guide"],
// 		]);
//
// 		const result = mergeNavMeta(existing, newSlugs, titles);
//
// 		// Should preserve custom title "🚀 Getting Started"
// 		expect(result.meta.introduction).toBe("🚀 Getting Started");
// 		// Order should be preserved
// 		const keys = Object.keys(result.meta);
// 		expect(keys).toEqual(["index", "introduction", "api-guide"]);
// 		// No entries should be removed
// 		expect(result.removedEntries).toEqual([]);
// 	});
// });
