/**
 * Localization content for ProfilePage.
 */
import { type Dictionary, t } from "intlayer";

const content = {
	key: "profile-page",
	content: {
		title: t({
			en: "Profile",
			es: "Perfil",
			fr: "Profil",
			de: "Profil",
			ja: "プロフィール",
			ko: "프로필",
			zh: "个人资料",
		}),
		subtitle: t({
			en: "Manage your personal information and account security.",
			es: "Administra tu información personal y seguridad de la cuenta.",
			fr: "Gérez vos informations personnelles et la sécurité de votre compte.",
			de: "Verwalten Sie Ihre persönlichen Daten und Kontosicherheit.",
			ja: "個人情報とアカウントのセキュリティを管理します。",
			ko: "개인 정보 및 계정 보안을 관리하세요.",
			zh: "管理您的个人信息和账户安全。",
		}),

		// Personal Information Section
		personalInfoTitle: t({
			en: "Personal Information",
			es: "Información personal",
			fr: "Informations personnelles",
			de: "Persönliche Informationen",
			ja: "個人情報",
			ko: "개인 정보",
			zh: "个人信息",
		}),
		personalInfoDescription: t({
			en: "Update your personal details.",
			es: "Actualiza tus datos personales.",
			fr: "Mettez à jour vos informations personnelles.",
			de: "Aktualisieren Sie Ihre persönlichen Daten.",
			ja: "個人情報を更新します。",
			ko: "개인 정보를 업데이트하세요.",
			zh: "更新您的个人信息。",
		}),

		// Profile Picture
		profilePictureLabel: t({
			en: "Profile Picture",
			es: "Foto de perfil",
			fr: "Photo de profil",
			de: "Profilbild",
			ja: "プロフィール画像",
			ko: "프로필 사진",
			zh: "头像",
		}),

		// Form Labels
		nameLabel: t({
			en: "Name",
			es: "Nombre",
			fr: "Nom",
			de: "Name",
			ja: "名前",
			ko: "이름",
			zh: "名称",
		}),
		namePlaceholder: t({
			en: "Enter your full name",
			es: "Ingresa tu nombre completo",
			fr: "Entrez votre nom complet",
			de: "Geben Sie Ihren vollständigen Namen ein",
			ja: "氏名を入力してください",
			ko: "전체 이름을 입력하세요",
			zh: "输入您的全名",
		}),
		emailLabel: t({
			en: "Email",
			es: "Correo electrónico",
			fr: "E-mail",
			de: "E-Mail",
			ja: "メール",
			ko: "이메일",
			zh: "电子邮件",
		}),
		emailHelperText: t({
			en: "Contact support to change your email address.",
			es: "Contacta a soporte para cambiar tu correo electrónico.",
			fr: "Contactez le support pour modifier votre adresse e-mail.",
			de: "Wenden Sie sich an den Support, um Ihre E-Mail-Adresse zu ändern.",
			ja: "メールアドレスを変更するには、サポートにお問い合わせください。",
			ko: "이메일 주소를 변경하려면 지원팀에 문의하세요.",
			zh: "如需更改电子邮件地址，请联系支持团队。",
		}),
		changeLink: t({
			en: "Change",
			es: "Cambiar",
			fr: "Modifier",
			de: "Ändern",
			ja: "変更",
			ko: "변경",
			zh: "修改",
		}),
		saveNameButton: t({
			en: "Save",
			es: "Guardar",
			fr: "Enregistrer",
			de: "Speichern",
			ja: "保存",
			ko: "저장",
			zh: "保存",
		}),
		nameUpdateSuccess: t({
			en: "Name updated successfully.",
			es: "Nombre actualizado correctamente.",
			fr: "Nom mis à jour avec succès.",
			de: "Name erfolgreich aktualisiert.",
			ja: "名前が正常に更新されました。",
			ko: "이름이 성공적으로 업데이트되었습니다.",
			zh: "名称更新成功。",
		}),
		nameUpdateError: t({
			en: "Failed to update name. Please try again.",
			es: "Error al actualizar el nombre. Por favor, inténtalo de nuevo.",
			fr: "Échec de la mise à jour du nom. Veuillez réessayer.",
			de: "Fehler beim Aktualisieren des Namens. Bitte versuchen Sie es erneut.",
			ja: "名前の更新に失敗しました。もう一度お試しください。",
			ko: "이름 업데이트에 실패했습니다. 다시 시도해 주세요.",
			zh: "更新名称失败。请重试。",
		}),

		// Password Section
		securityTitle: t({
			en: "Security",
			es: "Seguridad",
			fr: "Sécurité",
			de: "Sicherheit",
			ja: "セキュリティ",
			ko: "보안",
			zh: "安全",
		}),
		securityDescription: t({
			en: "Manage your password and security settings.",
			es: "Administra tu contraseña y configuración de seguridad.",
			fr: "Gérez votre mot de passe et vos paramètres de sécurité.",
			de: "Verwalten Sie Ihr Passwort und Ihre Sicherheitseinstellungen.",
			ja: "パスワードとセキュリティ設定を管理します。",
			ko: "비밀번호 및 보안 설정을 관리하세요.",
			zh: "管理您的密码和安全设置。",
		}),
		passwordLabel: t({
			en: "Password",
			es: "Contraseña",
			fr: "Mot de passe",
			de: "Passwort",
			ja: "パスワード",
			ko: "비밀번호",
			zh: "密码",
		}),
		passwordDescription: t({
			en: "Update your password to keep your account secure.",
			es: "Actualiza tu contraseña para mantener tu cuenta segura.",
			fr: "Mettez à jour votre mot de passe pour sécuriser votre compte.",
			de: "Aktualisieren Sie Ihr Passwort, um Ihr Konto zu schützen.",
			ja: "アカウントを安全に保つためにパスワードを更新してください。",
			ko: "계정을 안전하게 유지하려면 비밀번호를 업데이트하세요.",
			zh: "更新您的密码以确保账户安全。",
		}),
		changePasswordButton: t({
			en: "Change Password",
			es: "Cambiar contraseña",
			fr: "Changer le mot de passe",
			de: "Passwort ändern",
			ja: "パスワードを変更",
			ko: "비밀번호 변경",
			zh: "更改密码",
		}),
		setPasswordButton: t({
			en: "Set Password",
			es: "Establecer contraseña",
			fr: "Définir le mot de passe",
			de: "Passwort festlegen",
			ja: "パスワードを設定",
			ko: "비밀번호 설정",
			zh: "设置密码",
		}),
		passwordDescriptionNoPassword: t({
			en: "Set a password to enable password-based login in addition to your current login method.",
			es: "Establece una contraseña para habilitar el inicio de sesión con contraseña además de tu método de inicio de sesión actual.",
			fr: "Définissez un mot de passe pour activer la connexion par mot de passe en plus de votre méthode de connexion actuelle.",
			de: "Legen Sie ein Passwort fest, um die passwortbasierte Anmeldung zusätzlich zu Ihrer aktuellen Anmeldemethode zu aktivieren.",
			ja: "現在のログイン方法に加えて、パスワードログインを有効にするためのパスワードを設定してください。",
			ko: "현재 로그인 방법 외에 비밀번호 기반 로그인을 활성화하려면 비밀번호를 설정하세요.",
			zh: "设置密码以在您当前的登录方式之外启用密码登录。",
		}),

		// Buttons
		saveButton: t({
			en: "Save Changes",
			es: "Guardar cambios",
			fr: "Enregistrer les modifications",
			de: "Änderungen speichern",
			ja: "変更を保存",
			ko: "변경 사항 저장",
			zh: "保存更改",
		}),
		savingButton: t({
			en: "Saving...",
			es: "Guardando...",
			fr: "Enregistrement...",
			de: "Speichern...",
			ja: "保存中...",
			ko: "저장 중...",
			zh: "保存中...",
		}),

		// Messages
		saveSuccess: t({
			en: "Profile updated successfully.",
			es: "Perfil actualizado correctamente.",
			fr: "Profil mis à jour avec succès.",
			de: "Profil erfolgreich aktualisiert.",
			ja: "プロフィールが正常に更新されました。",
			ko: "프로필이 성공적으로 업데이트되었습니다.",
			zh: "个人资料更新成功。",
		}),
		saveError: t({
			en: "Failed to update profile. Please try again.",
			es: "Error al actualizar el perfil. Por favor, inténtalo de nuevo.",
			fr: "Échec de la mise à jour du profil. Veuillez réessayer.",
			de: "Fehler beim Aktualisieren des Profils. Bitte versuchen Sie es erneut.",
			ja: "プロフィールの更新に失敗しました。もう一度お試しください。",
			ko: "프로필 업데이트에 실패했습니다. 다시 시도해 주세요.",
			zh: "更新个人资料失败。请重试。",
		}),
		loadError: t({
			en: "Failed to load profile. Please refresh the page.",
			es: "Error al cargar el perfil. Por favor, actualiza la página.",
			fr: "Échec du chargement du profil. Veuillez rafraîchir la page.",
			de: "Fehler beim Laden des Profils. Bitte aktualisieren Sie die Seite.",
			ja: "プロフィールの読み込みに失敗しました。ページを更新してください。",
			ko: "프로필을 불러오는 데 실패했습니다. 페이지를 새로고침해 주세요.",
			zh: "加载个人资料失败。请刷新页面。",
		}),

		// Change Password Dialog
		changePasswordDialogTitle: t({
			en: "Change Password",
			es: "Cambiar contraseña",
			fr: "Changer le mot de passe",
			de: "Passwort ändern",
			ja: "パスワードを変更",
			ko: "비밀번호 변경",
			zh: "更改密码",
		}),
		changePasswordDialogDescription: t({
			en: "Enter your current password and a new password.",
			es: "Ingresa tu contraseña actual y una nueva contraseña.",
			fr: "Entrez votre mot de passe actuel et un nouveau mot de passe.",
			de: "Geben Sie Ihr aktuelles Passwort und ein neues Passwort ein.",
			ja: "現在のパスワードと新しいパスワードを入力してください。",
			ko: "현재 비밀번호와 새 비밀번호를 입력하세요.",
			zh: "输入您的当前密码和新密码。",
		}),
		currentPasswordLabel: t({
			en: "Current Password",
			es: "Contraseña actual",
			fr: "Mot de passe actuel",
			de: "Aktuelles Passwort",
			ja: "現在のパスワード",
			ko: "현재 비밀번호",
			zh: "当前密码",
		}),
		newPasswordLabel: t({
			en: "New Password",
			es: "Nueva contraseña",
			fr: "Nouveau mot de passe",
			de: "Neues Passwort",
			ja: "新しいパスワード",
			ko: "새 비밀번호",
			zh: "新密码",
		}),
		confirmPasswordLabel: t({
			en: "Confirm New Password",
			es: "Confirmar nueva contraseña",
			fr: "Confirmer le nouveau mot de passe",
			de: "Neues Passwort bestätigen",
			ja: "新しいパスワードを確認",
			ko: "새 비밀번호 확인",
			zh: "确认新密码",
		}),
		passwordMismatch: t({
			en: "Passwords do not match.",
			es: "Las contraseñas no coinciden.",
			fr: "Les mots de passe ne correspondent pas.",
			de: "Passwörter stimmen nicht überein.",
			ja: "パスワードが一致しません。",
			ko: "비밀번호가 일치하지 않습니다.",
			zh: "密码不匹配。",
		}),
		passwordRequirements: t({
			en: "Password must be 8-36 characters with uppercase, lowercase, number, and special character.",
			es: "La contraseña debe tener 8-36 caracteres con mayúsculas, minúsculas, números y caracteres especiales.",
			fr: "Le mot de passe doit contenir 8 à 36 caractères avec majuscule, minuscule, chiffre et caractère spécial.",
			de: "Das Passwort muss 8-36 Zeichen mit Groß- und Kleinbuchstaben, Zahl und Sonderzeichen enthalten.",
			ja: "パスワードは8～36文字で、大文字、小文字、数字、特殊文字を含む必要があります。",
			ko: "비밀번호는 대문자, 소문자, 숫자, 특수 문자를 포함한 8-36자여야 합니다.",
			zh: "密码必须是8-36个字符，包含大写字母、小写字母、数字和特殊字符。",
		}),
		cancelButton: t({
			en: "Cancel",
			es: "Cancelar",
			fr: "Annuler",
			de: "Abbrechen",
			ja: "キャンセル",
			ko: "취소",
			zh: "取消",
		}),
		updatePasswordButton: t({
			en: "Update Password",
			es: "Actualizar contraseña",
			fr: "Mettre à jour le mot de passe",
			de: "Passwort aktualisieren",
			ja: "パスワードを更新",
			ko: "비밀번호 업데이트",
			zh: "更新密码",
		}),
		updatingPasswordButton: t({
			en: "Updating...",
			es: "Actualizando...",
			fr: "Mise à jour...",
			de: "Aktualisieren...",
			ja: "更新中...",
			ko: "업데이트 중...",
			zh: "更新中...",
		}),
		passwordChangeSuccess: t({
			en: "Password changed successfully.",
			es: "Contraseña cambiada correctamente.",
			fr: "Mot de passe modifié avec succès.",
			de: "Passwort erfolgreich geändert.",
			ja: "パスワードが正常に変更されました。",
			ko: "비밀번호가 성공적으로 변경되었습니다.",
			zh: "密码更改成功。",
		}),
		passwordChangeError: t({
			en: "Failed to change password. Please check your current password and try again.",
			es: "Error al cambiar la contraseña. Por favor, verifica tu contraseña actual e inténtalo de nuevo.",
			fr: "Échec du changement de mot de passe. Veuillez vérifier votre mot de passe actuel et réessayer.",
			de: "Fehler beim Ändern des Passworts. Bitte überprüfen Sie Ihr aktuelles Passwort und versuchen Sie es erneut.",
			ja: "パスワードの変更に失敗しました。現在のパスワードを確認して、もう一度お試しください。",
			ko: "비밀번호 변경에 실패했습니다. 현재 비밀번호를 확인하고 다시 시도해 주세요.",
			zh: "更改密码失败。请检查您的当前密码并重试。",
		}),

		// Set Password Dialog (for OAuth-only users)
		setPasswordDialogTitle: t({
			en: "Set Password",
			es: "Establecer contraseña",
			fr: "Définir le mot de passe",
			de: "Passwort festlegen",
			ja: "パスワードを設定",
			ko: "비밀번호 설정",
			zh: "设置密码",
		}),
		setPasswordDialogDescription: t({
			en: "Create a password to enable password-based login for your account.",
			es: "Crea una contraseña para habilitar el inicio de sesión con contraseña para tu cuenta.",
			fr: "Créez un mot de passe pour activer la connexion par mot de passe pour votre compte.",
			de: "Erstellen Sie ein Passwort, um die passwortbasierte Anmeldung für Ihr Konto zu aktivieren.",
			ja: "アカウントのパスワードログインを有効にするためのパスワードを作成してください。",
			ko: "계정에 대한 비밀번호 기반 로그인을 활성화하려면 비밀번호를 만드세요.",
			zh: "创建密码以启用您账户的密码登录。",
		}),
		setPasswordButtonLabel: t({
			en: "Set Password",
			es: "Establecer contraseña",
			fr: "Définir le mot de passe",
			de: "Passwort festlegen",
			ja: "パスワードを設定",
			ko: "비밀번호 설정",
			zh: "设置密码",
		}),
		settingPasswordButton: t({
			en: "Setting...",
			es: "Estableciendo...",
			fr: "Définition...",
			de: "Festlegen...",
			ja: "設定中...",
			ko: "설정 중...",
			zh: "设置中...",
		}),
		setPasswordSuccess: t({
			en: "Password set successfully. You can now log in with your email and password.",
			es: "Contraseña establecida correctamente. Ahora puedes iniciar sesión con tu correo electrónico y contraseña.",
			fr: "Mot de passe défini avec succès. Vous pouvez maintenant vous connecter avec votre email et mot de passe.",
			de: "Passwort erfolgreich festgelegt. Sie können sich jetzt mit Ihrer E-Mail und Ihrem Passwort anmelden.",
			ja: "パスワードが正常に設定されました。メールアドレスとパスワードでログインできるようになりました。",
			ko: "비밀번호가 성공적으로 설정되었습니다. 이제 이메일과 비밀번호로 로그인할 수 있습니다.",
			zh: "密码设置成功。您现在可以使用电子邮件和密码登录。",
		}),
		setPasswordError: t({
			en: "Failed to set password. Please try again.",
			es: "Error al establecer la contraseña. Por favor, inténtalo de nuevo.",
			fr: "Échec de la définition du mot de passe. Veuillez réessayer.",
			de: "Fehler beim Festlegen des Passworts. Bitte versuchen Sie es erneut.",
			ja: "パスワードの設定に失敗しました。もう一度お試しください。",
			ko: "비밀번호 설정에 실패했습니다. 다시 시도해 주세요.",
			zh: "设置密码失败。请重试。",
		}),

		// Protection check messages
		noPasswordToChange: t({
			en: "No password is set for this account. Please use 'Set Password' instead.",
			es: "No hay contraseña establecida para esta cuenta. Por favor, usa 'Establecer contraseña' en su lugar.",
			fr: "Aucun mot de passe n'est défini pour ce compte. Veuillez utiliser 'Définir le mot de passe' à la place.",
			de: "Für dieses Konto ist kein Passwort festgelegt. Bitte verwenden Sie stattdessen 'Passwort festlegen'.",
			ja: "このアカウントにはパスワードが設定されていません。代わりに「パスワードを設定」を使用してください。",
			ko: "이 계정에 설정된 비밀번호가 없습니다. 대신 '비밀번호 설정'을 사용해 주세요.",
			zh: "此账户未设置密码。请改用设置密码。",
		}),
		passwordAlreadySet: t({
			en: "A password is already set. Please use 'Change Password' instead.",
			es: "Ya hay una contraseña establecida. Por favor, usa 'Cambiar contraseña' en su lugar.",
			fr: "Un mot de passe est déjà défini. Veuillez utiliser 'Changer le mot de passe' à la place.",
			de: "Ein Passwort ist bereits festgelegt. Bitte verwenden Sie stattdessen 'Passwort ändern'.",
			ja: "パスワードは既に設定されています。代わりに「パスワードを変更」を使用してください。",
			ko: "비밀번호가 이미 설정되어 있습니다. 대신 '비밀번호 변경'을 사용해 주세요.",
			zh: "密码已设置。请改用更改密码。",
		}),

		// Onboarding Section
		onboardingLabel: t({
			en: "Onboarding",
			es: "Incorporación",
			fr: "Intégration",
			de: "Einführung",
			ja: "オンボーディング",
			ko: "온보딩",
			zh: "引导流程",
		}),
		onboardingDescription: t({
			en: "Re-run the onboarding process to connect GitHub, import docs, or test auto-sync.",
			es: "Vuelve a ejecutar el proceso de incorporación para conectar GitHub, importar documentos o probar la sincronización automática.",
			fr: "Relancez le processus d'intégration pour connecter GitHub, importer des documents ou tester la synchronisation automatique.",
			de: "Führen Sie den Einführungsprozess erneut durch, um GitHub zu verbinden, Dokumente zu importieren oder die automatische Synchronisierung zu testen.",
			ja: "GitHubの接続、ドキュメントのインポート、または自動同期のテストを行うために、オンボーディングプロセスを再実行します。",
			ko: "GitHub 연결, 문서 가져오기 또는 자동 동기화 테스트를 위해 온보딩 프로세스를 다시 실행합니다.",
			zh: "重新运行引导流程以连接GitHub、导入文档或测试自动同步。",
		}),
		restartOnboardingButton: t({
			en: "Restart Onboarding",
			es: "Reiniciar incorporación",
			fr: "Relancer l'intégration",
			de: "Einführung neu starten",
			ja: "オンボーディングを再開",
			ko: "온보딩 다시 시작",
			zh: "重新开始引导",
		}),
		restartOnboardingSuccess: t({
			en: "Onboarding restarted successfully.",
			es: "Incorporación reiniciada correctamente.",
			fr: "Intégration relancée avec succès.",
			de: "Einführung erfolgreich neu gestartet.",
			ja: "オンボーディングが正常に再開されました。",
			ko: "온보딩이 성공적으로 다시 시작되었습니다.",
			zh: "引导流程已成功重新开始。",
		}),
		restartOnboardingError: t({
			en: "Failed to restart onboarding. Please try again.",
			es: "Error al reiniciar la incorporación. Por favor, inténtalo de nuevo.",
			fr: "Échec du relancement de l'intégration. Veuillez réessayer.",
			de: "Fehler beim Neustart der Einführung. Bitte versuchen Sie es erneut.",
			ja: "オンボーディングの再開に失敗しました。もう一度お試しください。",
			ko: "온보딩 다시 시작에 실패했습니다. 다시 시도해 주세요.",
			zh: "重新开始引导失败。请重试。",
		}),

		// Sessions Section
		sessionsLabel: t({
			en: "Sessions",
			es: "Sesiones",
			fr: "Sessions",
			de: "Sitzungen",
			ja: "セッション",
			ko: "세션",
			zh: "会话",
		}),
		sessionsDescription: t({
			en: "Manage your active sessions across devices.",
			es: "Administra tus sesiones activas en todos los dispositivos.",
			fr: "Gérez vos sessions actives sur tous les appareils.",
			de: "Verwalten Sie Ihre aktiven Sitzungen auf allen Geräten.",
			ja: "すべてのデバイスでアクティブなセッションを管理します。",
			ko: "모든 기기에서 활성 세션을 관리하세요.",
			zh: "管理您所有设备上的活动会话。",
		}),
		logoutAllSessionsButton: t({
			en: "Logout from all devices",
			es: "Cerrar sesión en todos los dispositivos",
			fr: "Déconnexion de tous les appareils",
			de: "Von allen Geräten abmelden",
			ja: "すべてのデバイスからログアウト",
			ko: "모든 기기에서 로그아웃",
			zh: "从所有设备注销",
		}),
		logoutAllSessionsDialogTitle: t({
			en: "Logout from all devices?",
			es: "¿Cerrar sesión en todos los dispositivos?",
			fr: "Déconnexion de tous les appareils?",
			de: "Von allen Geräten abmelden?",
			ja: "すべてのデバイスからログアウトしますか？",
			ko: "모든 기기에서 로그아웃하시겠습니까?",
			zh: "从所有设备注销？",
		}),
		logoutAllSessionsDialogDescription: t({
			en: "This will end all your active sessions, including this one. You will need to sign in again on all devices.",
			es: "Esto finalizará todas tus sesiones activas, incluida esta. Deberás iniciar sesión de nuevo en todos los dispositivos.",
			fr: "Cela mettra fin à toutes vos sessions actives, y compris celle-ci. Vous devrez vous reconnecter sur tous les appareils.",
			de: "Dies beendet alle Ihre aktiven Sitzungen, einschließlich dieser. Sie müssen sich auf allen Geräten erneut anmelden.",
			ja: "これにより、この端末を含むすべてのアクティブなセッションが終了します。すべてのデバイスで再度サインインする必要があります。",
			ko: "이 세션을 포함한 모든 활성 세션이 종료됩니다. 모든 기기에서 다시 로그인해야 합니다.",
			zh: "这将结束您所有的活动会话，包括当前会话。您需要在所有设备上重新登录。",
		}),
		confirmLogoutAllButton: t({
			en: "Logout from all devices",
			es: "Cerrar sesión en todos los dispositivos",
			fr: "Déconnexion de tous les appareils",
			de: "Von allen Geräten abmelden",
			ja: "すべてのデバイスからログアウト",
			ko: "모든 기기에서 로그아웃",
			zh: "从所有设备注销",
		}),
		loggingOutAllButton: t({
			en: "Logging out...",
			es: "Cerrando sesión...",
			fr: "Déconnexion...",
			de: "Abmelden...",
			ja: "ログアウト中...",
			ko: "로그아웃 중...",
			zh: "正在注销...",
		}),
		logoutAllSessionsSuccess: t({
			en: "Successfully logged out from all devices.",
			es: "Sesión cerrada correctamente en todos los dispositivos.",
			fr: "Déconnexion réussie de tous les appareils.",
			de: "Erfolgreich von allen Geräten abgemeldet.",
			ja: "すべてのデバイスからのログアウトに成功しました。",
			ko: "모든 기기에서 로그아웃되었습니다.",
			zh: "已成功从所有设备注销。",
		}),
		logoutAllSessionsError: t({
			en: "Failed to logout from all devices. Please try again.",
			es: "Error al cerrar sesión en todos los dispositivos. Por favor, inténtalo de nuevo.",
			fr: "Échec de la déconnexion de tous les appareils. Veuillez réessayer.",
			de: "Fehler beim Abmelden von allen Geräten. Bitte versuchen Sie es erneut.",
			ja: "すべてのデバイスからのログアウトに失敗しました。もう一度お試しください。",
			ko: "모든 기기에서 로그아웃에 실패했습니다. 다시 시도해 주세요.",
			zh: "从所有设备注销失败。请重试。",
		}),
	},
} satisfies Dictionary;

export default content;
