import AnthropicLLMClient from "../providers/Anthropic";
import type { Message } from "../Types";
import { e2bToolDefinitions } from "../tools/Tools";
import Agent, { type AgentOptions, type ChatOptions } from "./Agent";
import { getDefaultMaxOutputTokens } from "./defaults";
import { basename } from "node:path";

/**
 * Docs → Site agent (steps 5–7):
 * - Generates Docusaurus configuration from existing docs
 * - Deploys the docs to Vercel
 */
export function createDocsToSiteAgent(params: {
	runState?: AgentOptions["runState"];
	outputDir: string; // required path to docs directory generated by step 1–5
	projectName?: string; // optional override; defaults to <basename(outputDir)>-docs
}): {
	agent: Agent;
	withDefaults: (opts: ChatOptions) => ChatOptions;
} {
	const OUTDIR = params.outputDir;
	const defaultProjectName = `${basename(OUTDIR)}-docs`;
	const PROJECT = params.projectName || defaultProjectName;

	const systemPrompt = [
		"You are a precise documentation and deployment agent that generates Docusaurus configuration and publishes docs to Vercel.",
		"Execute steps 5–7 of the pipeline in sequence.",
		"Use the available tools: docs2docusaurus_run and docusaurus2vercel_run.",
	].join(" ");

	const userInstruction = `
Task: Generate Docusaurus configuration from existing docs and deploy to Vercel.

Context:
- Documentation has been synced to api-docs/docs/
- OUTDIR: ${OUTDIR}
- PROJECT_NAME: ${PROJECT}

Steps (perform 5–7 in sequence):
5) Call docs2docusaurus_run with:
   - docs_path: "api-docs/docs"
   - output_dir: "api-docs"
   - title: "API Documentation"
   - project: "${PROJECT}"

   This will generate Docusaurus configuration files (docusaurus.config.js, sidebars.js, package.json, etc.) in the api-docs directory.

6) Call docusaurus2vercel_run with:
   - docs_path: "api-docs"
   - project_name: "${PROJECT}"

   This will install dependencies, build the Docusaurus site, and deploy to Vercel.

7) Return a concise final summary including: CONFIG_DIR, DOCS_DIR, and deployment URL.

Constraints:
- Execute the tools in the order specified above
- Do not attempt to run code2docusaurus or checkout repos
- Keep logs minimal; provide key outputs and deployment URL
- If either tool fails, report the error and stop
`;

	const agent = new Agent({
		model: "claude-sonnet-4-5-20250929",
		temperature: 0.1,
		tools: e2bToolDefinitions,
		client: new AnthropicLLMClient(),
		maxOutputTokens: getDefaultMaxOutputTokens(),
		...(params.runState !== undefined ? { runState: params.runState } : {}),
	});

	const withDefaults = (opts: ChatOptions): ChatOptions => {
		const system = opts.system ?? systemPrompt;
		const messages: Array<Message> = opts.messages ?? [{ role: "user", content: userInstruction }];
		return { ...opts, system, messages };
	};

	return { agent, withDefaults };
}
