import { generateAuthLayout, generateAuthLib } from "./auth.js";
import { describe, expect, it } from "vitest";

describe("generateAuthLayout", () => {
	const defaultConfig = {
		logo: "Test Docs",
	};

	it("should generate app/layout.tsx with correct path", () => {
		const result = generateAuthLayout(defaultConfig, "test-site", "example.com");
		expect(result.path).toBe("app/layout.tsx");
	});

	it("should include Auth0Provider configuration", () => {
		const result = generateAuthLayout(defaultConfig, "test-site", "example.com");
		expect(result.content).toContain("Auth0Provider");
		expect(result.content).toContain("AUTH0_DOMAIN");
		expect(result.content).toContain("AUTH0_CLIENT_ID");
	});

	it("should include AuthGate with allowed domain", () => {
		const result = generateAuthLayout(defaultConfig, "test-site", "mycompany.com");
		expect(result.content).toContain('allowedDomain="mycompany.com"');
	});

	it("should import necessary dependencies", () => {
		const result = generateAuthLayout(defaultConfig, "test-site", "example.com");
		expect(result.content).toContain("'use client'");
		expect(result.content).toContain("import { Auth0Provider } from '@auth0/auth0-react'");
		expect(result.content).toContain("import { AuthGate } from '../lib/auth'");
	});

	it("should include Nextra layout components", () => {
		const result = generateAuthLayout(defaultConfig, "test-site", "example.com");
		expect(result.content).toContain("import { Footer, Layout, Navbar } from 'nextra-theme-docs'");
		expect(result.content).toContain("import { Head } from 'nextra/components'");
		expect(result.content).toContain("nextra-theme-docs/style.css");
	});

	it("should include logo in layout", () => {
		const config = { logo: "My Custom Logo" };
		const result = generateAuthLayout(config, "test-site", "example.com");
		expect(result.content).toContain("My Custom Logo");
	});

	it("should include footer text", () => {
		const config = { logo: "Test", footer: "© 2024 Test Co" };
		const result = generateAuthLayout(config, "test-site", "example.com");
		expect(result.content).toContain("© 2024 Test Co");
		expect(result.content).toContain("Generated by Jolli");
	});

	it("should include project link", () => {
		const config = { logo: "Test", projectLink: "https://github.com/test/repo" };
		const result = generateAuthLayout(config, "test-site", "example.com");
		expect(result.content).toContain("https://github.com/test/repo");
	});
});

describe("generateAuthLib", () => {
	it("should generate auth.tsx with correct path", () => {
		const result = generateAuthLib("example.com");
		expect(result.path).toBe("lib/auth.tsx");
	});

	it("should include AuthGate component", () => {
		const result = generateAuthLib("example.com");
		expect(result.content).toContain("export function AuthGate");
		expect(result.content).toContain("AuthGateProps");
	});

	it("should use client directive", () => {
		const result = generateAuthLib("example.com");
		expect(result.content).toContain("'use client'");
	});

	it("should check user email domain", () => {
		const result = generateAuthLib("example.com");
		expect(result.content).toContain("email.split('@')[1]");
		expect(result.content).toContain("userDomain === allowedDomain");
	});

	it("should show loading state", () => {
		const result = generateAuthLib("example.com");
		expect(result.content).toContain("Loading authentication...");
	});

	it("should show error state", () => {
		const result = generateAuthLib("example.com");
		expect(result.content).toContain("Authentication error:");
	});

	it("should show authentication required message with domain", () => {
		const result = generateAuthLib("mycompany.com");
		expect(result.content).toContain("restricted to @mycompany.com users");
	});

	it("should show access denied message", () => {
		const result = generateAuthLib("example.com");
		expect(result.content).toContain("Access Denied");
		expect(result.content).toContain("only accessible to users with @example.com email addresses");
	});

	it("should import useAuth0 hook", () => {
		const result = generateAuthLib("example.com");
		expect(result.content).toContain("import { useAuth0 } from '@auth0/auth0-react'");
	});
});
