import type { ThemeConfig } from "../types";
import * as appRouter from "./app-router";
import { describe, expect, it } from "vitest";

describe("App Router Templates", () => {
	const defaultTheme: ThemeConfig = {
		logo: "Test Logo",
		footer: "Test Footer",
	};

	describe("generatePackageJson", () => {
		it("should generate valid package.json", () => {
			const result = appRouter.generatePackageJson("my-docs");

			expect(result.path).toBe("package.json");
			const parsed = JSON.parse(result.content);
			expect(parsed.name).toBe("my-docs");
			expect(parsed.dependencies.next).toContain("15");
			expect(parsed.dependencies.nextra).toContain("4.");
			expect(parsed.dependencies.react).toContain("19");
		});

		it("should use default name if not provided", () => {
			const result = appRouter.generatePackageJson();

			const parsed = JSON.parse(result.content);
			expect(parsed.name).toBe("nextra-docs");
		});

		it("should include pagefind for search functionality in build script", () => {
			const result = appRouter.generatePackageJson("my-docs");

			const parsed = JSON.parse(result.content);
			expect(parsed.devDependencies.pagefind).toBeDefined();
			// Pagefind is chained in build script to ensure it runs on all platforms
			expect(parsed.scripts.build).toContain("pagefind");
			expect(parsed.scripts.build).toContain("public/_pagefind");
		});
	});

	describe("generateNextConfig", () => {
		it("should generate next.config.mjs", () => {
			const result = appRouter.generateNextConfig();

			expect(result.path).toBe("next.config.mjs");
			expect(result.content).toContain("import nextra from 'nextra'");
			expect(result.content).toContain("withNextra");
			expect(result.content).toContain("reactStrictMode: true");
		});

		it("should generate config without redirects when none provided", () => {
			const result = appRouter.generateNextConfig();

			expect(result.content).not.toContain("async redirects()");
			expect(result.content).not.toContain("source:");
			expect(result.content).not.toContain("destination:");
		});

		it("should generate config without redirects when empty array provided", () => {
			const result = appRouter.generateNextConfig([]);

			expect(result.content).not.toContain("async redirects()");
		});

		it("should generate config with redirects when provided", () => {
			const redirects = [
				{ source: "/import", destination: "/import-doc", permanent: true },
				{ source: "/interface", destination: "/interface-doc", permanent: true },
			];

			const result = appRouter.generateNextConfig(redirects);

			expect(result.content).toContain("async redirects()");
			expect(result.content).toContain("return [");
			expect(result.content).toContain("source: '/import'");
			expect(result.content).toContain("destination: '/import-doc'");
			expect(result.content).toContain("permanent: true");
			expect(result.content).toContain("source: '/interface'");
			expect(result.content).toContain("destination: '/interface-doc'");
		});

		it("should handle single redirect", () => {
			const redirects = [{ source: "/class", destination: "/class-doc", permanent: true }];

			const result = appRouter.generateNextConfig(redirects);

			expect(result.content).toContain("async redirects()");
			expect(result.content).toContain("source: '/class'");
		});
	});

	describe("generateTsConfig", () => {
		it("should generate valid tsconfig.json", () => {
			const result = appRouter.generateTsConfig();

			expect(result.path).toBe("tsconfig.json");
			const parsed = JSON.parse(result.content);
			expect(parsed.compilerOptions.strict).toBe(true);
			expect(parsed.compilerOptions.moduleResolution).toBe("bundler");
		});
	});

	describe("generateLayout", () => {
		it("should generate layout with theme config", () => {
			const result = appRouter.generateLayout(defaultTheme);

			expect(result.path).toBe("app/layout.tsx");
			expect(result.content).toContain("Test Logo");
			expect(result.content).toContain("Test Footer · Generated by Jolli");
			expect(result.content).toContain("nextra-theme-docs");
			expect(result.content).toContain("getPageMap");
		});

		it("should use default footer with logo if not provided", () => {
			const result = appRouter.generateLayout({ logo: "Logo" });

			expect(result.content).toContain("Logo · Generated by Jolli");
		});

		it("should include Discord chat link when chatLink is provided", () => {
			const result = appRouter.generateLayout({
				logo: "Logo",
				chatLink: "https://discord.gg/example",
			});

			expect(result.content).toContain('chatLink="https://discord.gg/example"');
			expect(result.content).toContain("chatIcon={");
			// Check for Discord icon SVG (partial match)
			expect(result.content).toContain('viewBox="0 0 16 16"');
		});

		it("should include Slack chat icon when chatIcon is slack", () => {
			const result = appRouter.generateLayout({
				logo: "Logo",
				chatLink: "https://slack.com/example",
				chatIcon: "slack",
			});

			expect(result.content).toContain('chatLink="https://slack.com/example"');
			// Slack icon has different path structure
			expect(result.content).toContain("M3.362 10.11");
		});

		it("should not include chat props when chatLink is not provided", () => {
			const result = appRouter.generateLayout({ logo: "Logo" });

			expect(result.content).not.toContain("chatLink=");
			expect(result.content).not.toContain("chatIcon=");
		});
	});

	describe("generateCatchAllPage", () => {
		it("should generate catch-all route page", () => {
			const result = appRouter.generateCatchAllPage();

			expect(result.path).toBe("app/[...mdxPath]/page.tsx");
			expect(result.content).toContain("generateStaticParamsFor");
			expect(result.content).toContain("importPage");
			expect(result.content).toContain("MDXContent");
		});

		it("should include force-static for Next.js 15+ compatibility", () => {
			const result = appRouter.generateCatchAllPage();

			expect(result.content).toContain("export const dynamic = 'force-static'");
		});
	});

	describe("generateMdxComponents", () => {
		it("should generate mdx-components.tsx", () => {
			const result = appRouter.generateMdxComponents();

			expect(result.path).toBe("mdx-components.tsx");
			expect(result.content).toContain("useMDXComponents");
			expect(result.content).toContain("getDocsMDXComponents");
		});
	});

	describe("generateIconComponent", () => {
		it("should generate dynamic icon component", () => {
			const result = appRouter.generateIconComponent();

			expect(result.path).toBe("app/icon.tsx");
			expect(result.content).toContain("ImageResponse");
			expect(result.content).toContain("contentType");
		});
	});

	describe("generateContentMeta", () => {
		it("should generate TypeScript meta file", () => {
			const result = appRouter.generateContentMeta({
				index: "Home",
				guide: "Guide",
			});

			expect(result.path).toBe("content/_meta.ts");
			expect(result.content).toContain("export default");
			expect(result.content).toContain("'index': 'Home'");
			expect(result.content).toContain("'guide': 'Guide'");
		});

		it("should generate TypeScript meta file with API page entries", () => {
			const result = appRouter.generateContentMeta({
				index: "Home",
				guide: "Guide",
				"api-petstore": {
					title: "Petstore API",
					type: "page",
					href: "/api-docs-petstore.html",
				},
			});

			expect(result.path).toBe("content/_meta.ts");
			expect(result.content).toContain("export default");
			expect(result.content).toContain("'index': 'Home'");
			expect(result.content).toContain("'guide': 'Guide'");
			// Check API page entry with object format
			expect(result.content).toContain("'api-petstore': {");
			expect(result.content).toContain("title: 'Petstore API'");
			expect(result.content).toContain("type: 'page'");
			expect(result.content).toContain("href: '/api-docs-petstore.html'");
		});

		it("should handle mixed string and object entries", () => {
			const result = appRouter.generateContentMeta({
				index: "Home",
				"api-users": {
					title: "Users API",
					type: "page",
					href: "/api-docs-users.html",
				},
				about: "About Us",
			});

			// Verify string entries use simple format
			expect(result.content).toContain("'index': 'Home'");
			expect(result.content).toContain("'about': 'About Us'");
			// Verify object entry uses complex format
			expect(result.content).toContain("'api-users': {");
		});

		it("should serialize virtual groups with nested items", () => {
			const result = appRouter.generateContentMeta({
				index: "Home",
				docs: {
					title: "Docs",
					type: "page",
					items: {
						introduction: "Introduction",
						"getting-started": "Getting Started",
					},
				},
			});

			expect(result.path).toBe("content/_meta.ts");
			expect(result.content).toContain("'index': 'Home'");
			expect(result.content).toContain("'docs': {");
			expect(result.content).toContain("title: 'Docs'");
			expect(result.content).toContain("type: 'page'");
			expect(result.content).toContain("items: {");
			expect(result.content).toContain("'introduction': 'Introduction'");
			expect(result.content).toContain("'getting-started': 'Getting Started'");
		});

		it("should serialize menu type virtual groups", () => {
			const result = appRouter.generateContentMeta({
				menu: {
					title: "Menu",
					type: "menu",
					items: {
						item1: "Item 1",
						item2: "Item 2",
					},
				},
			});

			expect(result.content).toContain("'menu': {");
			expect(result.content).toContain("title: 'Menu'");
			expect(result.content).toContain("type: 'menu'");
			expect(result.content).toContain("items: {");
		});

		it("should serialize separators", () => {
			const result = appRouter.generateContentMeta({
				index: "Home",
				"---": { type: "separator" },
				about: "About",
			});

			expect(result.content).toContain("'index': 'Home'");
			expect(result.content).toContain("'---': {");
			expect(result.content).toContain("type: 'separator'");
			expect(result.content).toContain("'about': 'About'");
		});

		it("should serialize separators with titles", () => {
			const result = appRouter.generateContentMeta({
				index: "Home",
				"-- docs": { type: "separator", title: "Docs" },
				introduction: "Introduction",
			});

			expect(result.content).toContain("'index': 'Home'");
			expect(result.content).toContain("'-- docs': {");
			expect(result.content).toContain("type: 'separator'");
			expect(result.content).toContain("title: 'Docs'");
			expect(result.content).toContain("'introduction': 'Introduction'");
		});

		it("should handle complex mixed structure", () => {
			const result = appRouter.generateContentMeta({
				index: "Home",
				docs: {
					title: "Docs",
					type: "page",
					items: {
						introduction: "Introduction",
					},
				},
				"---": { type: "separator" },
				"api-jolli": {
					title: "Jolli API",
					type: "page",
					href: "/api-docs-jolli.html",
				},
				"change-log": "Change Log",
			});

			// Verify all entry types are present
			expect(result.content).toContain("'index': 'Home'");
			expect(result.content).toContain("'docs': {");
			expect(result.content).toContain("items: {");
			expect(result.content).toContain("'introduction': 'Introduction'");
			expect(result.content).toContain("type: 'separator'");
			expect(result.content).toContain("href: '/api-docs-jolli.html'");
			expect(result.content).toContain("'change-log': 'Change Log'");
		});

		it("should serialize entries with nested theme objects", () => {
			const result = appRouter.generateContentMeta({
				index: "Home",
				tag: { theme: { layout: "full" } },
			});

			expect(result.content).toContain("'index': 'Home'");
			expect(result.content).toContain("'tag': {");
			expect(result.content).toContain("theme: {");
			expect(result.content).toContain("layout: 'full'");
			expect(result.content).not.toContain("[object Object]");
		});

		it("should serialize deeply nested objects", () => {
			const result = appRouter.generateContentMeta({
				page: {
					theme: {
						sidebar: false,
						layout: "full",
					},
				},
			});

			expect(result.content).toContain("'page': {");
			expect(result.content).toContain("theme: {");
			expect(result.content).toContain("sidebar: false");
			expect(result.content).toContain("layout: 'full'");
			expect(result.content).not.toContain("[object Object]");
		});
	});

	describe("generateIndexPage", () => {
		it("should generate index page with title", () => {
			const result = appRouter.generateIndexPage("My Docs");

			expect(result.path).toBe("content/index.mdx");
			expect(result.content).toContain("# My Docs");
			expect(result.content).toContain("Quick Links");
		});

		it("should use default title", () => {
			const result = appRouter.generateIndexPage();

			expect(result.content).toContain("# Welcome");
		});
	});

	describe("generateApiDocsHtml", () => {
		it("should generate API docs HTML", () => {
			const result = appRouter.generateApiDocsHtml();

			expect(result.path).toBe("public/api-docs.html");
			expect(result.content).toContain("@scalar/api-reference");
			expect(result.content).toContain("/openapi.json");
		});

		it("should use custom spec path", () => {
			const result = appRouter.generateApiDocsHtml("/custom/spec.json");

			expect(result.content).toContain("/custom/spec.json");
		});
	});

	describe("getBaseTemplates", () => {
		it("should return all base templates for full site", () => {
			const templates = appRouter.getBaseTemplates(defaultTheme, false);

			const paths = templates.map(t => t.path);
			expect(paths).toContain("package.json");
			expect(paths).toContain("next.config.mjs");
			expect(paths).toContain("tsconfig.json");
			expect(paths).toContain("app/layout.tsx");
			expect(paths).toContain("app/[...mdxPath]/page.tsx");
			expect(paths).toContain("mdx-components.tsx");
			expect(paths).toContain("content/_meta.ts");
			expect(paths).toContain("content/index.mdx");
			expect(paths).toContain("public/api-docs.html");
		});

		it("should return minimal templates when minimalContent is true", () => {
			const templates = appRouter.getBaseTemplates(defaultTheme, true);

			const paths = templates.map(t => t.path);
			expect(paths).toContain("package.json");
			// JOLLI-191: No content/index.mdx - app/page.tsx will redirect to first article
			expect(paths).not.toContain("content/index.mdx");
			expect(paths).toContain("content/_meta.ts");

			// Should NOT include sample pages
			expect(paths).not.toContain("public/api-docs.html");
		});

		it("should pass redirects to generateNextConfig", () => {
			const redirects = [{ source: "/import", destination: "/import-doc", permanent: true }];
			const templates = appRouter.getBaseTemplates(defaultTheme, false, undefined, redirects);

			const nextConfig = templates.find(t => t.path === "next.config.mjs");
			expect(nextConfig).toBeDefined();
			expect(nextConfig?.content).toContain("async redirects()");
			expect(nextConfig?.content).toContain("source: '/import'");
		});

		it("should not include redirects when not provided", () => {
			const templates = appRouter.getBaseTemplates(defaultTheme, false);

			const nextConfig = templates.find(t => t.path === "next.config.mjs");
			expect(nextConfig).toBeDefined();
			expect(nextConfig?.content).not.toContain("async redirects()");
		});
	});
});

describe("generateApiDocsPage", () => {
	it("should generate optional catch-all route for API docs", () => {
		const result = appRouter.generateApiDocsPage(["petstore", "users"]);

		expect(result.path).toBe("app/api-docs/[[...slug]]/page.tsx");
		expect(result.content).toContain("import { redirect, notFound }");
		expect(result.content).toContain("VALID_SLUGS = ['petstore', 'users']");
	});

	it("should generate static params with array format for catch-all", () => {
		const result = appRouter.generateApiDocsPage(["petstore", "users"]);

		expect(result.content).toContain("{ slug: [] }"); // Root redirect case
		expect(result.content).toContain("{ slug: ['petstore'] }");
		expect(result.content).toContain("{ slug: ['users'] }");
	});

	it("should redirect to first spec when no slug provided", () => {
		const result = appRouter.generateApiDocsPage(["petstore", "users"]);

		expect(result.content).toContain("if (slugArray.length === 0)");
		expect(result.content).toContain("redirect('/api-docs/petstore')");
	});

	it("should return 404 for invalid slugs", () => {
		const result = appRouter.generateApiDocsPage(["petstore"]);

		expect(result.content).toContain("if (!VALID_SLUGS.includes(slug))");
		expect(result.content).toContain("notFound()");
	});
});
