#!/usr/bin/env node
/**
 * Nextra Generator CLI
 *
 * A command-line tool for generating Nextra 4.x documentation sites.
 *
 * Usage:
 *   nextra-generator [options]
 *
 * Options:
 *   --output, -o        Output directory (required)
 *   --logo, -l          Site logo text (default: 'My Documentation')
 *   --logo-url          Image URL for logo
 *   --favicon           Favicon URL
 *   --primary-hue       Primary accent color hue 0-360 (default: 212)
 *   --footer, -f        Custom footer text (prepended to "Generated by Jolli")
 *   --default-theme     Default theme: 'dark', 'light', or 'system' (default: 'system')
 *   --project-link, -p  GitHub/project repository URL
 *   --chat-link         Discord/Slack community URL
 *   --chat-icon         Chat icon: 'discord' or 'slack' (default: 'discord')
 *   --hide-toc          Hide the right "On This Page" sidebar
 *   --toc-title         Custom TOC heading (default: 'On This Page')
 *   --sidebar-collapse  Sidebar collapse depth 1-6 (default: 2)
 *   --input, -i         Input directory to scan for files
 *   --openapi, -a       Path to OpenAPI spec file
 *   --skip-defaults     Skip generating default sample pages
 *   --help, -h          Show this help message
 *   --version, -v       Show version number
 *
 * Examples:
 *   # Generate a Nextra 4.x site
 *   nextra-generator -o ./my-docs
 *
 *   # Generate with custom branding
 *   nextra-generator -o ./my-docs -l "My API Docs" -f "© 2024 My Company"
 *
 *   # Generate with custom theme colors
 *   nextra-generator -o ./my-docs --primary-hue 270 --default-theme dark
 *
 *   # Generate from existing markdown files
 *   nextra-generator -o ./my-docs -i ./docs
 *
 *   # Generate with OpenAPI spec
 *   nextra-generator -o ./my-docs -a ./openapi.json
 */

import { generateSite } from "./generators/index.js";
import type {
	ChatIconType,
	DefaultThemeType,
	GeneratorConfig,
	InputFile,
	OpenApiConfig,
	RouterType,
	ThemeConfig,
} from "./types.js";
import { scanDirectory } from "./utils/input-files.js";

/** CLI argument definitions */
interface CliArgs {
	output?: string;
	logo: string;
	logoUrl?: string;
	favicon?: string;
	primaryHue?: number;
	footer?: string;
	defaultTheme?: DefaultThemeType;
	projectLink?: string;
	chatLink?: string;
	chatIcon?: ChatIconType;
	hideToc: boolean;
	tocTitle?: string;
	sidebarCollapse?: number;
	input?: string;
	openapi?: string;
	skipDefaults: boolean;
	help: boolean;
	version: boolean;
}

/** Parse command-line arguments */
function parseArgs(args: Array<string>): CliArgs {
	const result: CliArgs = {
		logo: "My Documentation",
		hideToc: false,
		skipDefaults: false,
		help: false,
		version: false,
	};

	for (let i = 0; i < args.length; i++) {
		const arg = args[i];
		const nextArg = args[i + 1];

		switch (arg) {
			case "--output":
			case "-o":
				result.output = nextArg;
				i++;
				break;
			case "--router":
			case "-r":
				// Router option is deprecated - Nextra 4.x App Router only
				console.warn("Warning: --router option is deprecated. Nextra 4.x App Router is now the only option.");
				i++;
				break;
			case "--logo":
			case "-l":
				result.logo = nextArg;
				i++;
				break;
			case "--logo-url":
				result.logoUrl = nextArg;
				i++;
				break;
			case "--favicon":
				result.favicon = nextArg;
				i++;
				break;
			case "--primary-hue": {
				const hue = Number.parseInt(nextArg, 10);
				if (Number.isNaN(hue) || hue < 0 || hue > 360) {
					console.error(`Invalid primary hue: ${nextArg}. Must be a number between 0 and 360.`);
					process.exit(1);
				}
				result.primaryHue = hue;
				i++;
				break;
			}
			case "--footer":
			case "-f":
				result.footer = nextArg;
				i++;
				break;
			case "--default-theme":
				if (nextArg === "dark" || nextArg === "light" || nextArg === "system") {
					result.defaultTheme = nextArg;
				} else {
					console.error(`Invalid default theme: ${nextArg}. Must be 'dark', 'light', or 'system'.`);
					process.exit(1);
				}
				i++;
				break;
			case "--project-link":
			case "-p":
				result.projectLink = nextArg;
				i++;
				break;
			case "--chat-link":
				result.chatLink = nextArg;
				i++;
				break;
			case "--chat-icon":
				if (nextArg === "discord" || nextArg === "slack") {
					result.chatIcon = nextArg;
				} else {
					console.error(`Invalid chat icon: ${nextArg}. Must be 'discord' or 'slack'.`);
					process.exit(1);
				}
				i++;
				break;
			case "--hide-toc":
				result.hideToc = true;
				break;
			case "--toc-title":
				result.tocTitle = nextArg;
				i++;
				break;
			case "--sidebar-collapse": {
				const level = Number.parseInt(nextArg, 10);
				if (Number.isNaN(level) || level < 1 || level > 6) {
					console.error(`Invalid sidebar collapse level: ${nextArg}. Must be between 1 and 6.`);
					process.exit(1);
				}
				result.sidebarCollapse = level;
				i++;
				break;
			}
			case "--input":
			case "-i":
				result.input = nextArg;
				i++;
				break;
			case "--openapi":
			case "-a":
				result.openapi = nextArg;
				i++;
				break;
			case "--skip-defaults":
				result.skipDefaults = true;
				break;
			case "--help":
			case "-h":
				result.help = true;
				break;
			case "--version":
			case "-v":
				result.version = true;
				break;
		}
	}

	return result;
}

/** Display help message */
function showHelp(): void {
	console.log(`
Nextra Generator CLI - Generate Nextra 4.x documentation sites

Usage:
  nextra-generator [options]

Options:
  --output, -o        Output directory (required)
  --logo, -l          Site logo text (default: 'My Documentation')
  --logo-url          Image URL for logo
  --favicon           Favicon URL
  --primary-hue       Primary accent color hue 0-360 (default: 212)
  --footer, -f        Custom footer text (prepended to "Generated by Jolli")
  --default-theme     Default theme: 'dark', 'light', or 'system' (default: 'system')
  --project-link, -p  GitHub/project repository URL
  --chat-link         Discord/Slack community URL
  --chat-icon         Chat icon: 'discord' or 'slack' (default: 'discord')
  --hide-toc          Hide the right "On This Page" sidebar
  --toc-title         Custom TOC heading (default: 'On This Page')
  --sidebar-collapse  Sidebar collapse depth 1-6 (default: 2)
  --input, -i         Input directory to scan for files (.md, .mdx, .json)
  --openapi, -a       Path to OpenAPI spec file (JSON format)
  --skip-defaults     Skip generating default sample pages
  --help, -h          Show this help message
  --version, -v       Show version number

Examples:
  # Generate a Nextra 4.x site with custom branding
  nextra-generator -o ./my-docs -l "My API Docs" -f "© 2024 My Company"

  # Generate with custom theme colors
  nextra-generator -o ./my-docs --primary-hue 270 --default-theme dark

  # Generate with logo image and Discord link
  nextra-generator -o ./my-docs --logo-url "https://example.com/logo.png" --chat-link "https://discord.gg/example"

  # Generate from existing markdown files
  nextra-generator -o ./my-docs -i ./docs

  # Generate with OpenAPI spec
  nextra-generator -o ./my-docs -a ./openapi.json

  # Generate minimal site (no sample pages)
  nextra-generator -o ./my-docs --skip-defaults

After generation:
  cd <output-dir>
  npm install
  npm run dev
`);
}

/** Display version */
function showVersion(): void {
	// Read version from package.json at runtime
	console.log("nextra-generator v2.0.0");
}

/** Main CLI entry point */
export async function main(args: Array<string> = process.argv.slice(2)): Promise<void> {
	const parsed = parseArgs(args);

	if (parsed.help) {
		showHelp();
		return;
	}

	if (parsed.version) {
		showVersion();
		return;
	}

	if (!parsed.output) {
		console.error("Error: Output directory is required. Use --output or -o to specify.");
		console.error("Run with --help for usage information.");
		process.exit(1);
	}

	// Build configuration - only include properties with defined values
	// to satisfy TypeScript's exactOptionalPropertyTypes
	const theme: ThemeConfig = {
		logo: parsed.logo,
		hideToc: parsed.hideToc,
	};
	if (parsed.logoUrl !== undefined) {
		theme.logoUrl = parsed.logoUrl;
	}
	if (parsed.favicon !== undefined) {
		theme.favicon = parsed.favicon;
	}
	if (parsed.primaryHue !== undefined) {
		theme.primaryHue = parsed.primaryHue;
	}
	if (parsed.footer !== undefined) {
		theme.footer = parsed.footer;
	}
	if (parsed.defaultTheme !== undefined) {
		theme.defaultTheme = parsed.defaultTheme;
	}
	if (parsed.projectLink !== undefined) {
		theme.projectLink = parsed.projectLink;
	}
	if (parsed.chatLink !== undefined) {
		theme.chatLink = parsed.chatLink;
	}
	if (parsed.chatIcon !== undefined) {
		theme.chatIcon = parsed.chatIcon;
	}
	if (parsed.tocTitle !== undefined) {
		theme.tocTitle = parsed.tocTitle;
	}
	if (parsed.sidebarCollapse !== undefined) {
		theme.sidebarDefaultCollapseLevel = parsed.sidebarCollapse;
	}

	const inputFiles: Array<InputFile> = [];
	const openApi: Array<OpenApiConfig> = [];

	// Scan input directory if provided
	if (parsed.input) {
		console.log(`Scanning input directory: ${parsed.input}`);
		const scannedFiles = await scanDirectory(parsed.input);
		inputFiles.push(...scannedFiles);
		console.log(`Found ${scannedFiles.length} files`);
	}

	// Add OpenAPI spec if provided
	if (parsed.openapi) {
		console.log(`Adding OpenAPI spec: ${parsed.openapi}`);
		openApi.push({
			specPath: parsed.openapi,
			outputPath: "api-reference",
			title: "API Reference",
		});
	}

	// Nextra 4.x uses App Router only
	const router: RouterType = "app";

	const config: GeneratorConfig = {
		router,
		outputDir: parsed.output,
		theme,
		skipDefaultPages: parsed.skipDefaults,
	};
	if (inputFiles.length > 0) {
		config.inputFiles = inputFiles;
	}
	if (openApi.length > 0) {
		config.openApi = openApi;
	}

	console.log(`\nGenerating Nextra 4.x site...`);
	console.log(`  Output: ${parsed.output}`);
	console.log(`  Logo: ${parsed.logo}`);

	const result = await generateSite(config);

	if (result.success) {
		console.log(`\n✓ Site generated successfully!`);
		console.log(`  Created ${result.filesCreated.length} files`);
		console.log(`\nNext steps:`);
		console.log(`  cd ${parsed.output}`);
		console.log(`  npm install`);
		console.log(`  npm run dev`);

		if (result.errors && result.errors.length > 0) {
			console.log(`\nWarnings:`);
			for (const error of result.errors) {
				console.log(`  ⚠ ${error}`);
			}
		}
	} else {
		console.error(`\n✗ Generation failed:`);
		if (result.errors) {
			for (const error of result.errors) {
				console.error(`  ${error}`);
			}
		}
		process.exit(1);
	}
}

// Run CLI if this file is executed directly
const isMainModule = process.argv[1]?.includes("Cli") || process.argv[1]?.includes("cli");
if (isMainModule) {
	main().catch(err => {
		console.error("Fatal error:", err);
		process.exit(1);
	});
}
