/**
 * Re-export OpenAPI types from jolli-common for external consumers
 */
export type {
	ApiEndpoint,
	ApiInfo,
	OpenApiOperation,
	OpenApiParsedSpec,
	OpenApiValidationError,
	OpenApiValidationResult,
} from "jolli-common";

/**
 * Router type for Nextra site generation
 */
export type RouterType = "app" | "page";

/**
 * Chat icon type for navbar
 */
export type ChatIconType = "discord" | "slack";

/**
 * Default theme type for site
 */
export type DefaultThemeType = "dark" | "light" | "system";

/**
 * Theme configuration options
 */
export interface ThemeConfig {
	/** Site logo text (used if logoUrl not provided) */
	logo: string;
	/** Image URL for logo (takes precedence over logo text) */
	logoUrl?: string;
	/** Favicon URL (defaults to generated "D" icon) */
	favicon?: string;
	/** Primary accent color hue 0-360 (default: 212 blue) */
	primaryHue?: number;
	/** Custom footer text - prepended to "Generated by Jolli" */
	footer?: string;
	/** Initial theme for visitors (default: 'system') */
	defaultTheme?: DefaultThemeType;
	/** GitHub or project repository link (defaults to Jolli-sample-repos/{siteName}) */
	projectLink?: string;
	/** Documentation repository base URL */
	docsRepositoryBase?: string;
	/** Discord/Slack community URL (no icon shown if not set) */
	chatLink?: string;
	/** Icon for chat link (default: 'discord', only used if chatLink is set) */
	chatIcon?: ChatIconType;
	/** Hide right "On This Page" sidebar (default: false) */
	hideToc?: boolean;
	/** Custom TOC heading (default: "On This Page") */
	tocTitle?: string;
	/** Sidebar collapse depth 1-6 (default: 2) */
	sidebarDefaultCollapseLevel?: number;
}

/**
 * Page metadata for navigation
 */
export interface PageMeta {
	/** Display title in navigation */
	title: string;
	/** Page type: 'page', 'menu', 'separator' */
	type?: "page" | "menu" | "separator";
	/** Hide from navigation */
	hidden?: boolean;
}

/**
 * API page metadata for external links (OpenAPI docs)
 * Used in _meta.ts for linking to standalone API documentation pages
 */
export interface ApiPageMeta {
	/** Display title in navigation */
	title: string;
	/** Page type - must be 'page' for external links */
	type: "page";
	/** URL to the API docs HTML page */
	href: string;
}

/**
 * Navigation structure
 */
export interface NavigationConfig {
	[key: string]: string | PageMeta;
}

/**
 * OpenAPI specification options
 */
export interface OpenApiConfig {
	/** Path to OpenAPI JSON/YAML file */
	specPath: string;
	/** Output page path (e.g., 'api-reference/interactive') */
	outputPath?: string;
	/** Page title */
	title?: string;
}

/**
 * Page content definition
 */
export interface PageConfig {
	/** Page path relative to content/pages folder */
	path: string;
	/** Page title for navigation */
	title: string;
	/** MDX content */
	content: string;
}

/**
 * Input file definition for importing existing files
 */
export interface InputFile {
	/** Absolute or relative path to the source file */
	sourcePath: string;
	/** Target path in the output (relative to content/pages folder) */
	targetPath?: string;
	/** Title for navigation (extracted from file if not provided) */
	title?: string;
}

/**
 * Supported input file types
 */
export type InputFileType = "mdx" | "md" | "json" | "yaml";

/**
 * Authentication configuration for domain-restricted sites (Auth0-based)
 */
export interface AuthConfig {
	/** Allowed email domain (e.g., "example.com") */
	allowedDomain: string;
}

/**
 * Article input for in-memory generation
 * Matches the structure from the backend Doc model
 */
export interface ArticleInput {
	/** Article content (markdown, JSON, or YAML) */
	content: string;
	/** Content type (e.g., "text/markdown", "application/json", "application/yaml") */
	contentType?: string;
	/** Content metadata including title, source info, etc. */
	contentMetadata?: ArticleMetadata;
	/** Last updated timestamp */
	updatedAt?: Date | string;
}

/**
 * Article metadata structure
 */
export interface ArticleMetadata {
	/** Article title */
	title?: string;
	/** Source name (e.g., "GitHub", "Confluence") */
	sourceName?: string;
	/** Source URL */
	sourceUrl?: string;
}

/**
 * File tree entry for in-memory generation
 * Compatible with the backend's FileTree structure
 */
export interface FileTree {
	/** File path relative to site root */
	path: string;
	/** File content */
	content: string;
}

/**
 * Existing files from the repository for migration
 */
export interface ExistingRepoFile {
	/** File path relative to repo root */
	path: string;
	/** File content */
	content: string;
}

/**
 * Re-export navigation meta types from jolli-common
 */
export type {
	ApiPageMetaEntry,
	ExistingNavMeta,
	ExistingNavMetaEntry,
	FlatNavMeta,
	SeparatorMeta,
	VirtualGroupMeta,
} from "jolli-common";

/**
 * Migration context for Nextra 3.x to 4.x upgrade
 */
export interface MigrationContext {
	/** Existing files from the repository */
	existingFiles?: Array<ExistingRepoFile>;
	/** Parsed theme config from theme.config.jsx */
	themeConfig?: Partial<ThemeConfig>;
	/** Existing navigation meta from _meta.ts (supports nested virtual groups) */
	existingNavMeta?: import("jolli-common").ExistingNavMeta;
	/** Slugs of deleted articles */
	deletedSlugs?: Array<string>;
	/** All folder _meta.ts files for multi-folder support */
	allFolderMetas?: Array<import("jolli-common").FolderMetaInfo>;
}

/**
 * Options for in-memory site generation
 */
export interface GenerateToMemoryOptions {
	/** Site name (used in package.json, etc.) */
	siteName: string;
	/** Display name shown in UI */
	displayName: string;
	/** Authentication configuration for Auth0-based domain restriction (optional) */
	auth?: AuthConfig;
	/** Regeneration mode - skip config files that should be preserved */
	regenerationMode?: boolean;
	/** Theme configuration overrides */
	theme?: Partial<ThemeConfig>;
	/** @deprecated No longer used. _meta.ts is always regenerated to ensure consistency. */
	navigationChanged?: boolean;
	/** Migration mode - regenerate ALL files including configs (for Nextra 3.x to 4.x migration). Overrides regenerationMode. */
	migrationMode?: boolean;
	/** Migration context with existing files and parsed config (for 3.x to 4.x migration) */
	migrationContext?: MigrationContext;
}

/**
 * Main generator configuration
 */
export interface GeneratorConfig {
	/** Router type: 'app' or 'page' */
	router: RouterType;
	/** Output directory for generated site */
	outputDir: string;
	/** Theme configuration */
	theme?: ThemeConfig;
	/** Initial pages to create */
	pages?: Array<PageConfig>;
	/** OpenAPI specifications to include */
	openApi?: Array<OpenApiConfig>;
	/** Input files to import (mdx, md, json) */
	inputFiles?: Array<InputFile>;
	/** Skip generating default pages (getting-started, api-reference) */
	skipDefaultPages?: boolean;
	/** Regeneration mode - use incremental _meta.js updates instead of full overwrite */
	regenerationMode?: boolean;
	/** Page keys to delete from _meta.js (for regeneration mode) */
	deletedPageKeys?: Array<string>;
}

/**
 * Generator result
 */
export interface GeneratorResult {
	success: boolean;
	outputDir: string;
	filesCreated: Array<string>;
	errors?: Array<string>;
}

/**
 * Template file definition
 */
export interface TemplateFile {
	/** Relative path within output directory */
	path: string;
	/** File content */
	content: string;
}

/**
 * OpenAPI spec info for generating navbar buttons and API views
 */
export interface OpenApiSpecInfo {
	/** Slug name for the spec (e.g., "petstore") - used in URLs and file names */
	name: string;
	/** Path to the spec file in public folder (e.g., "/petstore.json") */
	specPath: string;
	/** Display title for the API (e.g., "Petstore API") - used in navigation */
	title: string;
}

/**
 * OpenAPI specification structure (simplified for our use case)
 * Kept for backward compatibility, prefer OpenApiParsedSpec from jolli-common
 */
export interface OpenApiSpec {
	openapi?: string;
	swagger?: string;
	info?: {
		title?: string;
		version?: string;
		description?: string;
	};
	paths?: Record<
		string,
		Record<
			string,
			{
				summary?: string;
				description?: string;
				operationId?: string;
			}
		>
	>;
}

/**
 * Represents a deleted article for computing file paths to delete
 */
export interface DeletedArticle {
	/** Article title (used to compute the slug/file path) */
	title: string;
	/** Content type (e.g., "text/markdown", "application/json", "application/yaml") */
	contentType: string;
	/** Whether this was an OpenAPI spec (determines public/ vs pages/ location) */
	isOpenApi?: boolean;
}

/**
 * Redirect mapping for Next.js redirects configuration.
 * Used when a slug is sanitized (e.g., reserved words get `-doc` suffix)
 * to ensure old URLs redirect to the new safe URLs.
 */
export interface RedirectMapping {
	/** Source URL path (e.g., "/import") */
	source: string;
	/** Destination URL path (e.g., "/import-doc") */
	destination: string;
	/** Whether this is a permanent (308) or temporary (307) redirect */
	permanent: boolean;
}
